// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if GroundedGenerationService
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// Response message for the
  /// [GroundedGenerationService.CheckGrounding][google.cloud.discoveryengine.v1.GroundedGenerationService.CheckGrounding]
  /// method.
  ///
  /// [google.cloud.discoveryengine.v1.GroundedGenerationService.CheckGrounding]: <doc:GroundedGenerationServiceClient/checkGrounding(request:options:)>
  public struct CheckGroundingResponse: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The support score for the input answer candidate.
    /// Higher the score, higher is the fraction of claims that are supported by
    /// the provided facts. This is always set when a response is returned.
    public var supportScore: Swift.Float? = nil

    /// List of facts cited across all claims in the answer candidate.
    /// These are derived from the facts supplied in the request.
    public var citedChunks: [FactChunk] = []

    /// List of facts cited across all claims in the answer candidate.
    /// These are derived from the facts supplied in the request.
    public var citedFacts: [CheckGroundingResponse.CheckGroundingFactChunk] = []

    /// Claim texts and citation info across all claims in the answer candidate.
    public var claims: [CheckGroundingResponse.Claim] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `CheckGroundingResponse`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CheckGroundingResponse().with { $0.supportScore = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let supportScore = CodingKeys(stringValue: "supportScore")
      static let citedChunks = CodingKeys(stringValue: "citedChunks")
      static let citedFacts = CodingKeys(stringValue: "citedFacts")
      static let claims = CodingKeys(stringValue: "claims")

      static let _knownKeys: Set<Swift.String> = [
        "supportScore",
        "citedChunks",
        "citedFacts",
        "claims",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.supportScore = try container.decodeIfPresent(Swift.Float.self, forKey: .supportScore)
      if let value = try container.decodeIfPresent([FactChunk].self, forKey: .citedChunks) {
        self.citedChunks = value
      }
      if let value = try container.decodeIfPresent(
        [CheckGroundingResponse.CheckGroundingFactChunk].self, forKey: .citedFacts)
      {
        self.citedFacts = value
      }
      if let value = try container.decodeIfPresent(
        [CheckGroundingResponse.Claim].self, forKey: .claims)
      {
        self.claims = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.supportScore, forKey: .supportScore)
      try container.encode(self.citedChunks, forKey: .citedChunks)
      try container.encode(self.citedFacts, forKey: .citedFacts)
      try container.encode(self.claims, forKey: .claims)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Fact chunk for grounding check.
    public struct CheckGroundingFactChunk: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Text content of the fact chunk. Can be at most 10K characters long.
      public var chunkText: Swift.String = Swift.String()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `CheckGroundingFactChunk`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = CheckGroundingFactChunk().with { $0.chunkText = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let chunkText = CodingKeys(stringValue: "chunkText")

        static let _knownKeys: Set<Swift.String> = [
          "chunkText"
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .chunkText) {
          self.chunkText = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.Value.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.chunkText, forKey: .chunkText)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.discoveryengine.v1.CheckGroundingResponse.CheckGroundingFactChunk"
      }
      public init(fromAny any: GoogleWKT.`Any`) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.Struct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// Text and citation info for a claim in the answer candidate.
    public struct Claim: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Position indicating the start of the claim in the answer candidate,
      /// measured in bytes. Note that this is not measured in characters and,
      /// therefore, must be rendered in the user interface keeping in mind that
      /// some characters may take more than one byte. For example,
      /// if the claim text contains non-ASCII characters, the start and end
      /// positions vary when measured in characters
      /// (programming-language-dependent) and when measured in bytes
      /// (programming-language-independent).
      public var startPos: Swift.Int32? = nil

      /// Position indicating the end of the claim in the answer candidate,
      /// exclusive, in bytes. Note that this is not measured in characters and,
      /// therefore, must be rendered as such. For example, if the claim text
      /// contains non-ASCII characters, the start and end positions vary when
      /// measured in characters (programming-language-dependent) and when measured
      /// in bytes (programming-language-independent).
      public var endPos: Swift.Int32? = nil

      /// Text for the claim in the answer candidate. Always provided regardless of
      /// whether citations or anti-citations are found.
      public var claimText: Swift.String = Swift.String()

      /// A list of indices (into 'cited_chunks') specifying the citations
      /// associated with the claim. For instance [1,3,4] means that
      /// cited_chunks[1], cited_chunks[3], cited_chunks[4] are the facts cited
      /// supporting for the claim. A citation to a fact indicates that the claim
      /// is supported by the fact.
      public var citationIndices: [Swift.Int32] = []

      /// Indicates that this claim required grounding check. When the system
      /// decided this claim doesn't require attribution/grounding check, this
      /// field will be set to false. In that case, no grounding check was done for
      /// the claim and therefore
      /// [citation_indices][google.cloud.discoveryengine.v1.CheckGroundingResponse.Claim.citation_indices]
      /// should not be returned.
      ///
      /// [google.cloud.discoveryengine.v1.CheckGroundingResponse.Claim.citation_indices]: <doc:CheckGroundingResponse/Claim/citationIndices>
      public var groundingCheckRequired: Swift.Bool? = nil

      /// Confidence score for the claim in the answer candidate, in the range of
      /// [0, 1]. This is set only when
      /// `CheckGroundingRequest.grounding_spec.enable_claim_level_score` is true.
      public var score: Swift.Double? = nil

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `Claim`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Claim().with { $0.startPos = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let startPos = CodingKeys(stringValue: "startPos")
        static let endPos = CodingKeys(stringValue: "endPos")
        static let claimText = CodingKeys(stringValue: "claimText")
        static let citationIndices = CodingKeys(stringValue: "citationIndices")
        static let groundingCheckRequired = CodingKeys(stringValue: "groundingCheckRequired")
        static let score = CodingKeys(stringValue: "score")

        static let _knownKeys: Set<Swift.String> = [
          "startPos",
          "endPos",
          "claimText",
          "citationIndices",
          "groundingCheckRequired",
          "score",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.startPos = try container.decodeIfPresent(Swift.Int32.self, forKey: .startPos)
        self.endPos = try container.decodeIfPresent(Swift.Int32.self, forKey: .endPos)
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .claimText) {
          self.claimText = value
        }
        if let value = try container.decodeIfPresent([Swift.Int32].self, forKey: .citationIndices) {
          self.citationIndices = value
        }
        self.groundingCheckRequired = try container.decodeIfPresent(
          Swift.Bool.self, forKey: .groundingCheckRequired)
        self.score = try container.decodeIfPresent(Swift.Double.self, forKey: .score)
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.Value.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.startPos, forKey: .startPos)
        try container.encodeIfPresent(self.endPos, forKey: .endPos)
        try container.encode(self.claimText, forKey: .claimText)
        try container.encode(self.citationIndices, forKey: .citationIndices)
        try container.encodeIfPresent(self.groundingCheckRequired, forKey: .groundingCheckRequired)
        try container.encodeIfPresent(self.score, forKey: .score)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.discoveryengine.v1.CheckGroundingResponse.Claim"
      }
      public init(fromAny any: GoogleWKT.`Any`) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.Struct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.discoveryengine.v1.CheckGroundingResponse"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
