// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if CompletionService
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  import GoogleCloudWKT
  import GoogleLongRunning
  import GoogleRpc
  @_spi(GoogleCloudInternal) import GoogleCloudGax

  extension Clients {
    final class CompletionServiceTransport: CompletionServiceStub {
      let inner: GoogleCloudGax._HTTPClient

      public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
        self.inner = try GoogleCloudGax._HTTPClient(
          from: options,
          withDefaultEndpoint: "https://discoveryengine.googleapis.com",
        )
      }

      public func completeQuery(
        request: CompleteQueryRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryEngineV1.CompleteQueryResponse {
        let (path, query, configure) = try {
          () throws -> (
            Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
          ) in
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.dataStore as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/dataStores/"), .singleWildcard,
                ],
                fieldName: "data_store")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0):completeQuery"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleCloudGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.query, prefix: "query"))
            query.append(contentsOf: try encoder.encode(request.queryModel, prefix: "queryModel"))
            query.append(
              contentsOf: try encoder.encode(request.userPseudoId, prefix: "userPseudoId"))
            query.append(
              contentsOf: try encoder.encode(
                request.includeTailSuggestions, prefix: "includeTailSuggestions"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.dataStore as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                  .singleWildcard,
                ],
                fieldName: "data_store")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0):completeQuery"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleCloudGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.query, prefix: "query"))
            query.append(contentsOf: try encoder.encode(request.queryModel, prefix: "queryModel"))
            query.append(
              contentsOf: try encoder.encode(request.userPseudoId, prefix: "userPseudoId"))
            query.append(
              contentsOf: try encoder.encode(
                request.includeTailSuggestions, prefix: "includeTailSuggestions"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          var paths: [GoogleCloudGax.PathMismatch] = []
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.dataStore as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/dataStores/"), .singleWildcard,
              ],
              fieldName: "data_store",
              expecting: "projects/*/locations/*/dataStores/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.dataStore as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                .singleWildcard,
              ],
              fieldName: "data_store",
              expecting: "projects/*/locations/*/collections/*/dataStores/*"
            )
            paths.append(builder.build())
          }
          throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
        }()
        var req = try await self.inner.newRequest(
          percentEncodedPath: path, query: query, options: options)
        configure(&req)
        req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
        return try await req.rpc(
          GoogleCloudDiscoveryEngineV1.CompleteQueryResponse.self, timeout: options.attemptTimeout
        ).get()
      }

      public func importSuggestionDenyListEntries(
        request: ImportSuggestionDenyListEntriesRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation {
        let (path, query, configure) = try {
          () throws -> (
            Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
          ) in
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.parent as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                  .singleWildcard,
                ],
                fieldName: "parent")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/suggestionDenyListEntries:import"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.POST) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.parent as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/dataStores/"), .singleWildcard,
                ],
                fieldName: "parent")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/suggestionDenyListEntries:import"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.POST) })
          }
          var paths: [GoogleCloudGax.PathMismatch] = []
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                .singleWildcard,
              ],
              fieldName: "parent",
              expecting: "projects/*/locations/*/collections/*/dataStores/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/dataStores/"), .singleWildcard,
              ],
              fieldName: "parent",
              expecting: "projects/*/locations/*/dataStores/*"
            )
            paths.append(builder.build())
          }
          throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
        }()
        var req = try await self.inner.newRequest(
          percentEncodedPath: path, query: query, options: options)
        configure(&req)
        req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
        try req.setBody(json: request)
        return try await req.rpc(
          GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
        ).get()
      }

      public func purgeSuggestionDenyListEntries(
        request: PurgeSuggestionDenyListEntriesRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation {
        let (path, query, configure) = try {
          () throws -> (
            Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
          ) in
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.parent as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                  .singleWildcard,
                ],
                fieldName: "parent")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/suggestionDenyListEntries:purge"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.POST) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.parent as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/dataStores"), .trailingMultiWildcard,
                ],
                fieldName: "parent")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/suggestionDenyListEntries:purge"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.POST) })
          }
          var paths: [GoogleCloudGax.PathMismatch] = []
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                .singleWildcard,
              ],
              fieldName: "parent",
              expecting: "projects/*/locations/*/collections/*/dataStores/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/dataStores"), .trailingMultiWildcard,
              ],
              fieldName: "parent",
              expecting: "projects/*/locations/*/dataStores/**"
            )
            paths.append(builder.build())
          }
          throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
        }()
        var req = try await self.inner.newRequest(
          percentEncodedPath: path, query: query, options: options)
        configure(&req)
        req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
        try req.setBody(json: request)
        return try await req.rpc(
          GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
        ).get()
      }

      public func importCompletionSuggestions(
        request: ImportCompletionSuggestionsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation {
        let (path, query, configure) = try {
          () throws -> (
            Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
          ) in
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.parent as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                  .singleWildcard,
                ],
                fieldName: "parent")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/completionSuggestions:import"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.POST) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.parent as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/dataStores/"), .singleWildcard,
                ],
                fieldName: "parent")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/completionSuggestions:import"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.POST) })
          }
          var paths: [GoogleCloudGax.PathMismatch] = []
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                .singleWildcard,
              ],
              fieldName: "parent",
              expecting: "projects/*/locations/*/collections/*/dataStores/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/dataStores/"), .singleWildcard,
              ],
              fieldName: "parent",
              expecting: "projects/*/locations/*/dataStores/*"
            )
            paths.append(builder.build())
          }
          throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
        }()
        var req = try await self.inner.newRequest(
          percentEncodedPath: path, query: query, options: options)
        configure(&req)
        req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
        try req.setBody(json: request)
        return try await req.rpc(
          GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
        ).get()
      }

      public func purgeCompletionSuggestions(
        request: PurgeCompletionSuggestionsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation {
        let (path, query, configure) = try {
          () throws -> (
            Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
          ) in
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.parent as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                  .singleWildcard,
                ],
                fieldName: "parent")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/completionSuggestions:purge"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.POST) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.parent as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/dataStores/"), .singleWildcard,
                ],
                fieldName: "parent")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/completionSuggestions:purge"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.POST) })
          }
          var paths: [GoogleCloudGax.PathMismatch] = []
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                .singleWildcard,
              ],
              fieldName: "parent",
              expecting: "projects/*/locations/*/collections/*/dataStores/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/dataStores/"), .singleWildcard,
              ],
              fieldName: "parent",
              expecting: "projects/*/locations/*/dataStores/*"
            )
            paths.append(builder.build())
          }
          throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
        }()
        var req = try await self.inner.newRequest(
          percentEncodedPath: path, query: query, options: options)
        configure(&req)
        req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
        try req.setBody(json: request)
        return try await req.rpc(
          GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
        ).get()
      }

      public func listOperations(
        request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.ListOperationsResponse {
        let (path, query, configure) = try {
          () throws -> (
            Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
          ) in
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [.literal("projects/"), .singleWildcard],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/operations"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleCloudGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            query.append(
              contentsOf: try encoder.encode(
                request.returnPartialSuccess, prefix: "returnPartialSuccess"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/dataConnector"),
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/operations"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleCloudGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            query.append(
              contentsOf: try encoder.encode(
                request.returnPartialSuccess, prefix: "returnPartialSuccess"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                  .singleWildcard, .literal("/branches/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/operations"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleCloudGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            query.append(
              contentsOf: try encoder.encode(
                request.returnPartialSuccess, prefix: "returnPartialSuccess"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                  .singleWildcard, .literal("/models/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/operations"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleCloudGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            query.append(
              contentsOf: try encoder.encode(
                request.returnPartialSuccess, prefix: "returnPartialSuccess"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                  .singleWildcard, .literal("/schemas/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/operations"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleCloudGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            query.append(
              contentsOf: try encoder.encode(
                request.returnPartialSuccess, prefix: "returnPartialSuccess"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                  .singleWildcard, .literal("/siteSearchEngine/targetSites"),
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/operations"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleCloudGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            query.append(
              contentsOf: try encoder.encode(
                request.returnPartialSuccess, prefix: "returnPartialSuccess"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                  .singleWildcard, .literal("/siteSearchEngine"),
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/operations"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleCloudGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            query.append(
              contentsOf: try encoder.encode(
                request.returnPartialSuccess, prefix: "returnPartialSuccess"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                  .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/operations"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleCloudGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            query.append(
              contentsOf: try encoder.encode(
                request.returnPartialSuccess, prefix: "returnPartialSuccess"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/engines/"),
                  .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/operations"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleCloudGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            query.append(
              contentsOf: try encoder.encode(
                request.returnPartialSuccess, prefix: "returnPartialSuccess"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/operations"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleCloudGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            query.append(
              contentsOf: try encoder.encode(
                request.returnPartialSuccess, prefix: "returnPartialSuccess"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/dataStores/"), .singleWildcard, .literal("/branches/"),
                  .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/operations"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleCloudGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            query.append(
              contentsOf: try encoder.encode(
                request.returnPartialSuccess, prefix: "returnPartialSuccess"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/dataStores/"), .singleWildcard, .literal("/models/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/operations"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleCloudGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            query.append(
              contentsOf: try encoder.encode(
                request.returnPartialSuccess, prefix: "returnPartialSuccess"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/dataStores/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/operations"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleCloudGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            query.append(
              contentsOf: try encoder.encode(
                request.returnPartialSuccess, prefix: "returnPartialSuccess"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/identityMappingStores/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/operations"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleCloudGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            query.append(
              contentsOf: try encoder.encode(
                request.returnPartialSuccess, prefix: "returnPartialSuccess"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/operations"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleCloudGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            query.append(
              contentsOf: try encoder.encode(
                request.returnPartialSuccess, prefix: "returnPartialSuccess"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [.literal("projects/"), .singleWildcard],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/operations"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleCloudGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            query.append(
              contentsOf: try encoder.encode(
                request.returnPartialSuccess, prefix: "returnPartialSuccess"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          var paths: [GoogleCloudGax.PathMismatch] = []
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [.literal("projects/"), .singleWildcard],
              fieldName: "name",
              expecting: "projects/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/dataConnector"),
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/collections/*/dataConnector"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                .singleWildcard, .literal("/branches/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/collections/*/dataStores/*/branches/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                .singleWildcard, .literal("/models/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/collections/*/dataStores/*/models/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                .singleWildcard, .literal("/schemas/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/collections/*/dataStores/*/schemas/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                .singleWildcard, .literal("/siteSearchEngine/targetSites"),
              ],
              fieldName: "name",
              expecting:
                "projects/*/locations/*/collections/*/dataStores/*/siteSearchEngine/targetSites"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                .singleWildcard, .literal("/siteSearchEngine"),
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/collections/*/dataStores/*/siteSearchEngine"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/collections/*/dataStores/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/engines/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/collections/*/engines/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/collections/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/dataStores/"), .singleWildcard, .literal("/branches/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/dataStores/*/branches/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/dataStores/"), .singleWildcard, .literal("/models/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/dataStores/*/models/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/dataStores/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/dataStores/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/identityMappingStores/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/identityMappingStores/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [.literal("projects/"), .singleWildcard],
              fieldName: "name",
              expecting: "projects/*"
            )
            paths.append(builder.build())
          }
          throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
        }()
        var req = try await self.inner.newRequest(
          percentEncodedPath: path, query: query, options: options)
        configure(&req)
        req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
        return try await req.rpc(
          GoogleLongRunning.ListOperationsResponse.self, timeout: options.attemptTimeout
        ).get()
      }

      public func getOperation(
        request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation {
        let (path, query, configure) = try {
          () throws -> (
            Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
          ) in
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/operations/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard,
                  .literal("/dataConnector/operations/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                  .singleWildcard, .literal("/branches/"), .singleWildcard,
                  .literal("/operations/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                  .singleWildcard, .literal("/models/"), .singleWildcard, .literal("/operations/"),
                  .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                  .singleWildcard, .literal("/operations/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                  .singleWildcard, .literal("/schemas/"), .singleWildcard, .literal("/operations/"),
                  .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                  .singleWildcard, .literal("/siteSearchEngine/operations/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                  .singleWildcard, .literal("/siteSearchEngine/targetSites/operations/"),
                  .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/engines/"),
                  .singleWildcard, .literal("/operations/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/operations/"),
                  .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/dataStores/"), .singleWildcard, .literal("/branches/"),
                  .singleWildcard, .literal("/operations/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/dataStores/"), .singleWildcard, .literal("/models/"), .singleWildcard,
                  .literal("/operations/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/dataStores/"), .singleWildcard, .literal("/operations/"),
                  .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/identityMappingStores/"), .singleWildcard, .literal("/operations/"),
                  .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/operations/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/operations/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          var paths: [GoogleCloudGax.PathMismatch] = []
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/operations/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/dataConnector/operations/"),
                .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/collections/*/dataConnector/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                .singleWildcard, .literal("/branches/"), .singleWildcard, .literal("/operations/"),
                .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/collections/*/dataStores/*/branches/*/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                .singleWildcard, .literal("/models/"), .singleWildcard, .literal("/operations/"),
                .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/collections/*/dataStores/*/models/*/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                .singleWildcard, .literal("/operations/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/collections/*/dataStores/*/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                .singleWildcard, .literal("/schemas/"), .singleWildcard, .literal("/operations/"),
                .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/collections/*/dataStores/*/schemas/*/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                .singleWildcard, .literal("/siteSearchEngine/operations/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting:
                "projects/*/locations/*/collections/*/dataStores/*/siteSearchEngine/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                .singleWildcard, .literal("/siteSearchEngine/targetSites/operations/"),
                .singleWildcard,
              ],
              fieldName: "name",
              expecting:
                "projects/*/locations/*/collections/*/dataStores/*/siteSearchEngine/targetSites/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/engines/"), .singleWildcard,
                .literal("/operations/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/collections/*/engines/*/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/operations/"),
                .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/collections/*/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/dataStores/"), .singleWildcard, .literal("/branches/"), .singleWildcard,
                .literal("/operations/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/dataStores/*/branches/*/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/dataStores/"), .singleWildcard, .literal("/models/"), .singleWildcard,
                .literal("/operations/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/dataStores/*/models/*/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/dataStores/"), .singleWildcard, .literal("/operations/"),
                .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/dataStores/*/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/identityMappingStores/"), .singleWildcard, .literal("/operations/"),
                .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/identityMappingStores/*/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/operations/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/operations/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/operations/*"
            )
            paths.append(builder.build())
          }
          throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
        }()
        var req = try await self.inner.newRequest(
          percentEncodedPath: path, query: query, options: options)
        configure(&req)
        req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
        return try await req.rpc(
          GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
        ).get()
      }

      public func cancelOperation(
        request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws {
        let (path, query, configure) = try {
          () throws -> (
            Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
          ) in
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/operations/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0):cancel"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.POST) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                  .singleWildcard, .literal("/branches/"), .singleWildcard,
                  .literal("/operations/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0):cancel"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.POST) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/engines/"),
                  .singleWildcard, .literal("/operations/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0):cancel"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.POST) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/dataStores/"), .singleWildcard, .literal("/branches/"),
                  .singleWildcard, .literal("/operations/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0):cancel"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.POST) })
          }
          var paths: [GoogleCloudGax.PathMismatch] = []
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/operations/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                .singleWildcard, .literal("/branches/"), .singleWildcard, .literal("/operations/"),
                .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/collections/*/dataStores/*/branches/*/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/engines/"), .singleWildcard,
                .literal("/operations/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/collections/*/engines/*/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleCloudGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/dataStores/"), .singleWildcard, .literal("/branches/"), .singleWildcard,
                .literal("/operations/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/dataStores/*/branches/*/operations/*"
            )
            paths.append(builder.build())
          }
          throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
        }()
        var req = try await self.inner.newRequest(
          percentEncodedPath: path, query: query, options: options)
        configure(&req)
        req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
        try req.setBody(json: request)
        _ = try await req.rpc(
          GoogleCloudWKT.Empty.self, timeout: options.attemptTimeout
        ).get()
      }
    }
  }
#endif
