// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if ConversationalSearchService
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  import GoogleCloudWkt
  import GoogleLongrunning
  import GoogleCloudGax

  extension Clients {
    protocol ConversationalSearchServiceStub {
      func converseConversation(
        request: ConverseConversationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.ConverseConversationResponse

      func createConversation(
        request: CreateConversationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.Conversation

      func deleteConversation(
        request: DeleteConversationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws

      func updateConversation(
        request: UpdateConversationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.Conversation

      func getConversation(
        request: GetConversationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.Conversation

      func listConversations(
        request: ListConversationsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.ListConversationsResponse

      func answerQuery(
        request: AnswerQueryRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.AnswerQueryResponse

      func streamAnswerQuery(
        request: AnswerQueryRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.AnswerQueryResponse

      func getAnswer(
        request: GetAnswerRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.Answer

      func createSession(
        request: CreateSessionRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.Session

      func deleteSession(
        request: DeleteSessionRequest, options: GoogleCloudGax.RequestOptions
      ) async throws

      func updateSession(
        request: UpdateSessionRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.Session

      func getSession(
        request: GetSessionRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.Session

      func listSessions(
        request: ListSessionsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.ListSessionsResponse

      func listOperations(
        request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongrunning.ListOperationsResponse

      func getOperation(
        request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongrunning.Operation

      func cancelOperation(
        request: GoogleLongrunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws
    }

    class ConversationalSearchServiceTransport: ConversationalSearchServiceStub {
      let inner: GoogleCloudGax.HTTPClient

      public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
        self.inner = try GoogleCloudGax.HTTPClient(
          from: options, withDefaultEndpoint: "https://discoveryengine.googleapis.com")
      }

      public func converseConversation(
        request: ConverseConversationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.ConverseConversationResponse {
        let path = try { () throws -> Swift.String in
          guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
            throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
          }
          return "/v1/\(pathVariable0):converse"
        }()
        let query = [
          URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
        ]
        var req = try await self.inner.Request(path: path, query: query)
        req.httpMethod = "POST"
        req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.httpBody = try JSONEncoder().encode(request)
        let (data, _) = try await self.inner.rpc(for: req).get()
        return try GoogleCloudWkt._ProtoJSONDecoder().decode(
          GoogleCloudDiscoveryengineV1.ConverseConversationResponse.self, from: data)
      }

      public func createConversation(
        request: CreateConversationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.Conversation {
        let path = try { () throws -> Swift.String in
          guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
            throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
          }
          return "/v1/\(pathVariable0)/conversations"
        }()
        let query = [
          URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
        ]
        var req = try await self.inner.Request(path: path, query: query)
        req.httpMethod = "POST"
        req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
        if let body = request.conversation {
          req.setValue("application/json", forHTTPHeaderField: "Content-Type")
          req.httpBody = try JSONEncoder().encode(body)
        }
        let (data, _) = try await self.inner.rpc(for: req).get()
        return try GoogleCloudWkt._ProtoJSONDecoder().decode(
          GoogleCloudDiscoveryengineV1.Conversation.self, from: data)
      }

      public func deleteConversation(
        request: DeleteConversationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws {
        let path = try { () throws -> Swift.String in
          guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
            throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
          }
          return "/v1/\(pathVariable0)"
        }()
        let query = [
          URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
        ]
        var req = try await self.inner.Request(path: path, query: query)
        req.httpMethod = "DELETE"
        req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
        _ = try await self.inner.rpc(for: req).get()
      }

      public func updateConversation(
        request: UpdateConversationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.Conversation {
        let path = try { () throws -> Swift.String in
          guard let pathVariable0 = request.conversation.map({ $0.name }), !pathVariable0.isEmpty
          else {
            throw GoogleCloudGax.RequestError.binding(
              "'request.conversation.name' is not set or is empty")
          }
          return "/v1/\(pathVariable0)"
        }()
        var query = [
          URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
        ]
        let encoder = GoogleCloudGax.QueryParameterEncoder()
        query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
        var req = try await self.inner.Request(path: path, query: query)
        req.httpMethod = "PATCH"
        req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
        if let body = request.conversation {
          req.setValue("application/json", forHTTPHeaderField: "Content-Type")
          req.httpBody = try JSONEncoder().encode(body)
        }
        let (data, _) = try await self.inner.rpc(for: req).get()
        return try GoogleCloudWkt._ProtoJSONDecoder().decode(
          GoogleCloudDiscoveryengineV1.Conversation.self, from: data)
      }

      public func getConversation(
        request: GetConversationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.Conversation {
        let path = try { () throws -> Swift.String in
          guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
            throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
          }
          return "/v1/\(pathVariable0)"
        }()
        let query = [
          URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
        ]
        var req = try await self.inner.Request(path: path, query: query)
        req.httpMethod = "GET"
        req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
        let (data, _) = try await self.inner.rpc(for: req).get()
        return try GoogleCloudWkt._ProtoJSONDecoder().decode(
          GoogleCloudDiscoveryengineV1.Conversation.self, from: data)
      }

      public func listConversations(
        request: ListConversationsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.ListConversationsResponse {
        let path = try { () throws -> Swift.String in
          guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
            throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
          }
          return "/v1/\(pathVariable0)/conversations"
        }()
        var query = [
          URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
        ]
        let encoder = GoogleCloudGax.QueryParameterEncoder()
        query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
        query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
        query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
        query.append(contentsOf: try encoder.encode(request.orderBy, prefix: "orderBy"))
        var req = try await self.inner.Request(path: path, query: query)
        req.httpMethod = "GET"
        req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
        let (data, _) = try await self.inner.rpc(for: req).get()
        return try GoogleCloudWkt._ProtoJSONDecoder().decode(
          GoogleCloudDiscoveryengineV1.ListConversationsResponse.self, from: data)
      }

      public func answerQuery(
        request: AnswerQueryRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.AnswerQueryResponse {
        let path = try { () throws -> Swift.String in
          guard let pathVariable0 = request.servingConfig as Swift.String?, !pathVariable0.isEmpty
          else {
            throw GoogleCloudGax.RequestError.binding(
              "'request.serving_config' is not set or is empty")
          }
          return "/v1/\(pathVariable0):answer"
        }()
        let query = [
          URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
        ]
        var req = try await self.inner.Request(path: path, query: query)
        req.httpMethod = "POST"
        req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.httpBody = try JSONEncoder().encode(request)
        let (data, _) = try await self.inner.rpc(for: req).get()
        return try GoogleCloudWkt._ProtoJSONDecoder().decode(
          GoogleCloudDiscoveryengineV1.AnswerQueryResponse.self, from: data)
      }

      public func streamAnswerQuery(
        request: AnswerQueryRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.AnswerQueryResponse {
        let path = try { () throws -> Swift.String in
          guard let pathVariable0 = request.servingConfig as Swift.String?, !pathVariable0.isEmpty
          else {
            throw GoogleCloudGax.RequestError.binding(
              "'request.serving_config' is not set or is empty")
          }
          return "/v1/\(pathVariable0):streamAnswer"
        }()
        let query = [
          URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
        ]
        var req = try await self.inner.Request(path: path, query: query)
        req.httpMethod = "POST"
        req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.httpBody = try JSONEncoder().encode(request)
        let (data, _) = try await self.inner.rpc(for: req).get()
        return try GoogleCloudWkt._ProtoJSONDecoder().decode(
          GoogleCloudDiscoveryengineV1.AnswerQueryResponse.self, from: data)
      }

      public func getAnswer(
        request: GetAnswerRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.Answer {
        let path = try { () throws -> Swift.String in
          guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
            throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
          }
          return "/v1/\(pathVariable0)"
        }()
        let query = [
          URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
        ]
        var req = try await self.inner.Request(path: path, query: query)
        req.httpMethod = "GET"
        req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
        let (data, _) = try await self.inner.rpc(for: req).get()
        return try GoogleCloudWkt._ProtoJSONDecoder().decode(
          GoogleCloudDiscoveryengineV1.Answer.self, from: data)
      }

      public func createSession(
        request: CreateSessionRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.Session {
        let path = try { () throws -> Swift.String in
          guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
            throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
          }
          return "/v1/\(pathVariable0)/sessions"
        }()
        let query = [
          URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
        ]
        var req = try await self.inner.Request(path: path, query: query)
        req.httpMethod = "POST"
        req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
        if let body = request.session {
          req.setValue("application/json", forHTTPHeaderField: "Content-Type")
          req.httpBody = try JSONEncoder().encode(body)
        }
        let (data, _) = try await self.inner.rpc(for: req).get()
        return try GoogleCloudWkt._ProtoJSONDecoder().decode(
          GoogleCloudDiscoveryengineV1.Session.self, from: data)
      }

      public func deleteSession(
        request: DeleteSessionRequest, options: GoogleCloudGax.RequestOptions
      ) async throws {
        let path = try { () throws -> Swift.String in
          guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
            throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
          }
          return "/v1/\(pathVariable0)"
        }()
        let query = [
          URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
        ]
        var req = try await self.inner.Request(path: path, query: query)
        req.httpMethod = "DELETE"
        req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
        _ = try await self.inner.rpc(for: req).get()
      }

      public func updateSession(
        request: UpdateSessionRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.Session {
        let path = try { () throws -> Swift.String in
          guard let pathVariable0 = request.session.map({ $0.name }), !pathVariable0.isEmpty else {
            throw GoogleCloudGax.RequestError.binding(
              "'request.session.name' is not set or is empty")
          }
          return "/v1/\(pathVariable0)"
        }()
        var query = [
          URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
        ]
        let encoder = GoogleCloudGax.QueryParameterEncoder()
        query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
        var req = try await self.inner.Request(path: path, query: query)
        req.httpMethod = "PATCH"
        req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
        if let body = request.session {
          req.setValue("application/json", forHTTPHeaderField: "Content-Type")
          req.httpBody = try JSONEncoder().encode(body)
        }
        let (data, _) = try await self.inner.rpc(for: req).get()
        return try GoogleCloudWkt._ProtoJSONDecoder().decode(
          GoogleCloudDiscoveryengineV1.Session.self, from: data)
      }

      public func getSession(
        request: GetSessionRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.Session {
        let path = try { () throws -> Swift.String in
          guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
            throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
          }
          return "/v1/\(pathVariable0)"
        }()
        var query = [
          URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
        ]
        let encoder = GoogleCloudGax.QueryParameterEncoder()
        query.append(
          contentsOf: try encoder.encode(
            request.includeAnswerDetails, prefix: "includeAnswerDetails"))
        var req = try await self.inner.Request(path: path, query: query)
        req.httpMethod = "GET"
        req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
        let (data, _) = try await self.inner.rpc(for: req).get()
        return try GoogleCloudWkt._ProtoJSONDecoder().decode(
          GoogleCloudDiscoveryengineV1.Session.self, from: data)
      }

      public func listSessions(
        request: ListSessionsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.ListSessionsResponse {
        let path = try { () throws -> Swift.String in
          guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
            throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
          }
          return "/v1/\(pathVariable0)/sessions"
        }()
        var query = [
          URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
        ]
        let encoder = GoogleCloudGax.QueryParameterEncoder()
        query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
        query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
        query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
        query.append(contentsOf: try encoder.encode(request.orderBy, prefix: "orderBy"))
        var req = try await self.inner.Request(path: path, query: query)
        req.httpMethod = "GET"
        req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
        let (data, _) = try await self.inner.rpc(for: req).get()
        return try GoogleCloudWkt._ProtoJSONDecoder().decode(
          GoogleCloudDiscoveryengineV1.ListSessionsResponse.self, from: data)
      }

      public func listOperations(
        request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongrunning.ListOperationsResponse {
        let path = try { () throws -> Swift.String in
          guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
            throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
          }
          return "/v1/\(pathVariable0)/operations"
        }()
        var query = [
          URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
        ]
        let encoder = GoogleCloudGax.QueryParameterEncoder()
        query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
        query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
        query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
        query.append(
          contentsOf: try encoder.encode(
            request.returnPartialSuccess, prefix: "returnPartialSuccess"))
        var req = try await self.inner.Request(path: path, query: query)
        req.httpMethod = "GET"
        req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
        let (data, _) = try await self.inner.rpc(for: req).get()
        return try GoogleCloudWkt._ProtoJSONDecoder().decode(
          GoogleLongrunning.ListOperationsResponse.self, from: data)
      }

      public func getOperation(
        request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongrunning.Operation {
        let path = try { () throws -> Swift.String in
          guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
            throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
          }
          return "/v1/\(pathVariable0)"
        }()
        let query = [
          URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
        ]
        var req = try await self.inner.Request(path: path, query: query)
        req.httpMethod = "GET"
        req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
        let (data, _) = try await self.inner.rpc(for: req).get()
        return try GoogleCloudWkt._ProtoJSONDecoder().decode(
          GoogleLongrunning.Operation.self, from: data)
      }

      public func cancelOperation(
        request: GoogleLongrunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws {
        let path = try { () throws -> Swift.String in
          guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
            throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
          }
          return "/v1/\(pathVariable0):cancel"
        }()
        let query = [
          URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
        ]
        var req = try await self.inner.Request(path: path, query: query)
        req.httpMethod = "POST"
        req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.httpBody = try JSONEncoder().encode(request)
        _ = try await self.inner.rpc(for: req).get()
      }
    }
  }
#endif
