// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if ConversationalSearchService
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  import GoogleCloudWkt
  import GoogleLongrunning
  import GoogleCloudGax
  import struct Logging.Logger

  extension Clients {
    final class ConversationalSearchServiceLogging: ConversationalSearchServiceStub {
      let inner: any ConversationalSearchServiceStub
      let logger: Logger

      public init(_ inner: any ConversationalSearchServiceStub, logger: Logger) {
        var logger = logger
        logger[metadataKey: "gcp.artifact.id"] = "GoogleCloudDiscoveryengineV1"
        logger[metadataKey: "gcp.client.service"] = "discoveryengine"
        logger[metadataKey: "gcp.experimental.swift.client"] = "ConversationalSearchService"
        self.inner = inner
        self.logger = logger
      }

      func _intercept<Input, Output>(
        request: Input,
        options: GoogleCloudGax.RequestOptions,
        name: Swift.String,
        action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
      ) async throws -> Output {
        var logger = logger
        logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
        logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
        logger.debug("enter  : \(request) \(options)")
        do {
          let output = try await action(request, options)
          logger.debug("success: \(request) \(options) \(output)")
          return output
        } catch let error {
          logger.debug("error  : \(request) \(options) \(error)")
          throw error
        }
      }

      public func converseConversation(
        request: ConverseConversationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.ConverseConversationResponse {
        try await self._intercept(
          request: request,
          options: options,
          name: "converseConversation",
          action: {
            (r: ConverseConversationRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudDiscoveryengineV1.ConverseConversationResponse
            in
            return try await self.inner.converseConversation(request: r, options: o)
          })
      }

      public func createConversation(
        request: CreateConversationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.Conversation {
        try await self._intercept(
          request: request,
          options: options,
          name: "createConversation",
          action: {
            (r: CreateConversationRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudDiscoveryengineV1.Conversation
            in
            return try await self.inner.createConversation(request: r, options: o)
          })
      }

      public func deleteConversation(
        request: DeleteConversationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws {
        try await self._intercept(
          request: request,
          options: options,
          name: "deleteConversation",
          action: {
            (r: DeleteConversationRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
            return try await self.inner.deleteConversation(request: r, options: o)
          })
      }

      public func updateConversation(
        request: UpdateConversationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.Conversation {
        try await self._intercept(
          request: request,
          options: options,
          name: "updateConversation",
          action: {
            (r: UpdateConversationRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudDiscoveryengineV1.Conversation
            in
            return try await self.inner.updateConversation(request: r, options: o)
          })
      }

      public func getConversation(
        request: GetConversationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.Conversation {
        try await self._intercept(
          request: request,
          options: options,
          name: "getConversation",
          action: {
            (r: GetConversationRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudDiscoveryengineV1.Conversation
            in
            return try await self.inner.getConversation(request: r, options: o)
          })
      }

      public func listConversations(
        request: ListConversationsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.ListConversationsResponse {
        try await self._intercept(
          request: request,
          options: options,
          name: "listConversations",
          action: {
            (r: ListConversationsRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudDiscoveryengineV1.ListConversationsResponse
            in
            return try await self.inner.listConversations(request: r, options: o)
          })
      }

      public func answerQuery(
        request: AnswerQueryRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.AnswerQueryResponse {
        try await self._intercept(
          request: request,
          options: options,
          name: "answerQuery",
          action: {
            (r: AnswerQueryRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudDiscoveryengineV1.AnswerQueryResponse
            in
            return try await self.inner.answerQuery(request: r, options: o)
          })
      }

      public func streamAnswerQuery(
        request: AnswerQueryRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.AnswerQueryResponse {
        try await self._intercept(
          request: request,
          options: options,
          name: "streamAnswerQuery",
          action: {
            (r: AnswerQueryRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudDiscoveryengineV1.AnswerQueryResponse
            in
            return try await self.inner.streamAnswerQuery(request: r, options: o)
          })
      }

      public func getAnswer(
        request: GetAnswerRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.Answer {
        try await self._intercept(
          request: request,
          options: options,
          name: "getAnswer",
          action: {
            (r: GetAnswerRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudDiscoveryengineV1.Answer
            in
            return try await self.inner.getAnswer(request: r, options: o)
          })
      }

      public func createSession(
        request: CreateSessionRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.Session {
        try await self._intercept(
          request: request,
          options: options,
          name: "createSession",
          action: {
            (r: CreateSessionRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudDiscoveryengineV1.Session
            in
            return try await self.inner.createSession(request: r, options: o)
          })
      }

      public func deleteSession(
        request: DeleteSessionRequest, options: GoogleCloudGax.RequestOptions
      ) async throws {
        try await self._intercept(
          request: request,
          options: options,
          name: "deleteSession",
          action: {
            (r: DeleteSessionRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
            return try await self.inner.deleteSession(request: r, options: o)
          })
      }

      public func updateSession(
        request: UpdateSessionRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.Session {
        try await self._intercept(
          request: request,
          options: options,
          name: "updateSession",
          action: {
            (r: UpdateSessionRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudDiscoveryengineV1.Session
            in
            return try await self.inner.updateSession(request: r, options: o)
          })
      }

      public func getSession(
        request: GetSessionRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.Session {
        try await self._intercept(
          request: request,
          options: options,
          name: "getSession",
          action: {
            (r: GetSessionRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudDiscoveryengineV1.Session
            in
            return try await self.inner.getSession(request: r, options: o)
          })
      }

      public func listSessions(
        request: ListSessionsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.ListSessionsResponse {
        try await self._intercept(
          request: request,
          options: options,
          name: "listSessions",
          action: {
            (r: ListSessionsRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudDiscoveryengineV1.ListSessionsResponse
            in
            return try await self.inner.listSessions(request: r, options: o)
          })
      }

      public func listOperations(
        request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongrunning.ListOperationsResponse {
        try await self._intercept(
          request: request,
          options: options,
          name: "listOperations",
          action: {
            (r: GoogleLongrunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleLongrunning.ListOperationsResponse
            in
            return try await self.inner.listOperations(request: r, options: o)
          })
      }

      public func getOperation(
        request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongrunning.Operation {
        try await self._intercept(
          request: request,
          options: options,
          name: "getOperation",
          action: {
            (r: GoogleLongrunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleLongrunning.Operation
            in
            return try await self.inner.getOperation(request: r, options: o)
          })
      }

      public func cancelOperation(
        request: GoogleLongrunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws {
        try await self._intercept(
          request: request,
          options: options,
          name: "cancelOperation",
          action: {
            (r: GoogleLongrunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> Void in
            return try await self.inner.cancelOperation(request: r, options: o)
          })
      }
    }
  }
#endif
