// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if DocumentService
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  import GoogleCloudWkt
  import GoogleLongRunning
  import GoogleRpc
  import GoogleCloudGax

  /// Service for ingesting [Document][google.cloud.discoveryengine.v1.Document]
  /// information of the customer's website.
  ///
  /// [google.cloud.discoveryengine.v1.Document]: <doc:Document>
  ///
  /// @Snippet(path: "DocumentServiceQuickstart")
  public class DocumentServiceClient: Clients.DocumentServiceProtocol {
    let inner: any Clients.DocumentServiceStub
    let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
    let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

    /// Creates a new `DocumentServiceClient` instance.
    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      var inner: any Clients.DocumentServiceStub = try Clients.DocumentServiceTransport(options)
      inner = Clients.DocumentServiceRetry(inner, options: options)
      if let logger = options.logger {
        inner = Clients.DocumentServiceLogging(inner, logger: logger)
      }
      self.inner = inner
      self.pollingErrorPolicy = options.pollingErrorPolicy
      self.pollingBackoffPolicy = options.pollingBackoffPolicy
    }

    /// Gets a [Document][google.cloud.discoveryengine.v1.Document].
    ///
    /// [google.cloud.discoveryengine.v1.Document]: <doc:Document>
    ///
    /// @Snippet(path: "DocumentService_GetDocument")
    public func getDocument(
      request: GetDocumentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDiscoveryEngineV1.Document {
      try await self.inner.getDocument(request: request, options: options)
    }

    /// Gets a list of [Document][google.cloud.discoveryengine.v1.Document]s.
    ///
    /// [google.cloud.discoveryengine.v1.Document]: <doc:Document>
    ///
    /// @Snippet(path: "DocumentService_ListDocuments")
    public func listDocuments(
      request: ListDocumentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDiscoveryEngineV1.ListDocumentsResponse {
      try await self.inner.listDocuments(request: request, options: options)
    }

    /// Gets a list of [Document][google.cloud.discoveryengine.v1.Document]s.
    ///
    /// [google.cloud.discoveryengine.v1.Document]: <doc:Document>
    ///
    /// @Snippet(path: "DocumentService_ListDocuments")
    public func listDocuments(
      byItem: ListDocumentsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Document, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws -> GoogleCloudDiscoveryEngineV1.ListDocumentsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listDocuments(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// Creates a [Document][google.cloud.discoveryengine.v1.Document].
    ///
    /// [google.cloud.discoveryengine.v1.Document]: <doc:Document>
    ///
    /// @Snippet(path: "DocumentService_CreateDocument")
    public func createDocument(
      request: CreateDocumentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDiscoveryEngineV1.Document {
      try await self.inner.createDocument(request: request, options: options)
    }

    /// Updates a [Document][google.cloud.discoveryengine.v1.Document].
    ///
    /// [google.cloud.discoveryengine.v1.Document]: <doc:Document>
    ///
    /// @Snippet(path: "DocumentService_UpdateDocument")
    public func updateDocument(
      request: UpdateDocumentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDiscoveryEngineV1.Document {
      try await self.inner.updateDocument(request: request, options: options)
    }

    /// Deletes a [Document][google.cloud.discoveryengine.v1.Document].
    ///
    /// [google.cloud.discoveryengine.v1.Document]: <doc:Document>
    ///
    /// @Snippet(path: "DocumentService_DeleteDocument")
    public func deleteDocument(
      request: DeleteDocumentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self.inner.deleteDocument(request: request, options: options)
    }

    /// Bulk import of multiple
    /// [Document][google.cloud.discoveryengine.v1.Document]s. Request processing
    /// may be synchronous. Non-existing items are created.
    ///
    /// Note: It is possible for a subset of the
    /// [Document][google.cloud.discoveryengine.v1.Document]s to be successfully
    /// updated.
    ///
    /// [google.cloud.discoveryengine.v1.Document]: <doc:Document>
    ///
    /// @Snippet(path: "DocumentService_ImportDocuments")
    public func importDocuments(
      request: ImportDocumentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self.inner.importDocuments(request: request, options: options)
    }

    /// Bulk import of multiple
    /// [Document][google.cloud.discoveryengine.v1.Document]s. Request processing
    /// may be synchronous. Non-existing items are created.
    ///
    /// Note: It is possible for a subset of the
    /// [Document][google.cloud.discoveryengine.v1.Document]s to be successfully
    /// updated.
    ///
    /// [google.cloud.discoveryengine.v1.Document]: <doc:Document>
    ///
    /// @Snippet(path: "DocumentService_ImportDocuments")
    public func importDocuments(
      withPolling: ImportDocumentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<ImportDocumentsResponse> {
      let extractStatus = {
        (op: GoogleLongRunning.Operation) throws
          -> GoogleCloudGax._PollableOperationImpl<ImportDocumentsResponse>.State in
        return try op._extractStatus(ImportDocumentsResponse.self)
      }
      let rawOp = try await self.importDocuments(request: withPolling, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = {
        () async throws -> GoogleCloudGax._PollableOperationImpl<ImportDocumentsResponse>.State in
        let op = try await self.getOperation(
          request: .init().with { $0.name = rawOp.name }, options: options)
        return try extractStatus(op)
      }
      return GoogleCloudGax._PollableOperationImpl(
        initialState: initialState,
        polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
        backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
        poll: poll,
      )
    }

    /// Permanently deletes all selected
    /// [Document][google.cloud.discoveryengine.v1.Document]s in a branch.
    ///
    /// This process is asynchronous. Depending on the number of
    /// [Document][google.cloud.discoveryengine.v1.Document]s to be deleted, this
    /// operation can take hours to complete. Before the delete operation
    /// completes, some [Document][google.cloud.discoveryengine.v1.Document]s might
    /// still be returned by
    /// [DocumentService.GetDocument][google.cloud.discoveryengine.v1.DocumentService.GetDocument]
    /// or
    /// [DocumentService.ListDocuments][google.cloud.discoveryengine.v1.DocumentService.ListDocuments].
    ///
    /// To get a list of the [Document][google.cloud.discoveryengine.v1.Document]s
    /// to be deleted, set
    /// [PurgeDocumentsRequest.force][google.cloud.discoveryengine.v1.PurgeDocumentsRequest.force]
    /// to false.
    ///
    /// [google.cloud.discoveryengine.v1.Document]: <doc:Document>
    /// [google.cloud.discoveryengine.v1.DocumentService.GetDocument]: <doc:DocumentServiceClient/getDocument(request:options:)>
    /// [google.cloud.discoveryengine.v1.DocumentService.ListDocuments]: <doc:DocumentServiceClient/listDocuments(request:options:)>
    /// [google.cloud.discoveryengine.v1.PurgeDocumentsRequest.force]: <doc:PurgeDocumentsRequest/force>
    ///
    /// @Snippet(path: "DocumentService_PurgeDocuments")
    public func purgeDocuments(
      request: PurgeDocumentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self.inner.purgeDocuments(request: request, options: options)
    }

    /// Permanently deletes all selected
    /// [Document][google.cloud.discoveryengine.v1.Document]s in a branch.
    ///
    /// This process is asynchronous. Depending on the number of
    /// [Document][google.cloud.discoveryengine.v1.Document]s to be deleted, this
    /// operation can take hours to complete. Before the delete operation
    /// completes, some [Document][google.cloud.discoveryengine.v1.Document]s might
    /// still be returned by
    /// [DocumentService.GetDocument][google.cloud.discoveryengine.v1.DocumentService.GetDocument]
    /// or
    /// [DocumentService.ListDocuments][google.cloud.discoveryengine.v1.DocumentService.ListDocuments].
    ///
    /// To get a list of the [Document][google.cloud.discoveryengine.v1.Document]s
    /// to be deleted, set
    /// [PurgeDocumentsRequest.force][google.cloud.discoveryengine.v1.PurgeDocumentsRequest.force]
    /// to false.
    ///
    /// [google.cloud.discoveryengine.v1.Document]: <doc:Document>
    /// [google.cloud.discoveryengine.v1.DocumentService.GetDocument]: <doc:DocumentServiceClient/getDocument(request:options:)>
    /// [google.cloud.discoveryengine.v1.DocumentService.ListDocuments]: <doc:DocumentServiceClient/listDocuments(request:options:)>
    /// [google.cloud.discoveryengine.v1.PurgeDocumentsRequest.force]: <doc:PurgeDocumentsRequest/force>
    ///
    /// @Snippet(path: "DocumentService_PurgeDocuments")
    public func purgeDocuments(
      withPolling: PurgeDocumentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<PurgeDocumentsResponse> {
      let extractStatus = {
        (op: GoogleLongRunning.Operation) throws
          -> GoogleCloudGax._PollableOperationImpl<PurgeDocumentsResponse>.State in
        return try op._extractStatus(PurgeDocumentsResponse.self)
      }
      let rawOp = try await self.purgeDocuments(request: withPolling, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = {
        () async throws -> GoogleCloudGax._PollableOperationImpl<PurgeDocumentsResponse>.State in
        let op = try await self.getOperation(
          request: .init().with { $0.name = rawOp.name }, options: options)
        return try extractStatus(op)
      }
      return GoogleCloudGax._PollableOperationImpl(
        initialState: initialState,
        polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
        backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
        poll: poll,
      )
    }

    /// Gets index freshness metadata for
    /// [Document][google.cloud.discoveryengine.v1.Document]s. Supported for
    /// website search only.
    ///
    /// [google.cloud.discoveryengine.v1.Document]: <doc:Document>
    ///
    /// @Snippet(path: "DocumentService_BatchGetDocumentsMetadata")
    public func batchGetDocumentsMetadata(
      request: BatchGetDocumentsMetadataRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDiscoveryEngineV1.BatchGetDocumentsMetadataResponse {
      try await self.inner.batchGetDocumentsMetadata(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "DocumentService_ListOperations")
    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self.inner.listOperations(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "DocumentService_ListOperations")
    public func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listOperations(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "DocumentService_GetOperation")
    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self.inner.getOperation(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "DocumentService_CancelOperation")
    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self.inner.cancelOperation(request: request, options: options)
    }
  }

  extension Clients {
    /// A Swift protocol to mock `DocumentServiceClient`.
    ///
    /// To mock `DocumentServiceClient` change your functions to receive
    /// `some DocumentServiceProtocol` or `any DocumentServiceProtocol`
    /// and pass a mock implementation in your tests.
    public protocol DocumentServiceProtocol {
      /// See `DocumentServiceClient.getDocument`.
      func getDocument(request: GetDocumentRequest) async throws
        -> GoogleCloudDiscoveryEngineV1.Document

      /// See `DocumentServiceClient.getDocument`.
      func getDocument(
        name: Swift.String,
      ) async throws -> GoogleCloudDiscoveryEngineV1.Document

      /// See `DocumentServiceClient.listDocuments`.
      func listDocuments(request: ListDocumentsRequest) async throws
        -> GoogleCloudDiscoveryEngineV1.ListDocumentsResponse

      /// See `DocumentServiceClient.listDocuments`.
      func listDocuments(
        byItem: ListDocumentsRequest
      ) throws -> any AsyncSequence<Document, Swift.Error>

      /// See `DocumentServiceClient.listDocuments`.
      func listDocuments(
        parent: Swift.String,
      ) throws -> any AsyncSequence<Document, Swift.Error>

      /// See `DocumentServiceClient.createDocument`.
      func createDocument(request: CreateDocumentRequest) async throws
        -> GoogleCloudDiscoveryEngineV1.Document

      /// See `DocumentServiceClient.createDocument`.
      func createDocument(
        parent: Swift.String,
        document: Document?,
        documentId: Swift.String,
      ) async throws -> GoogleCloudDiscoveryEngineV1.Document

      /// See `DocumentServiceClient.updateDocument`.
      func updateDocument(request: UpdateDocumentRequest) async throws
        -> GoogleCloudDiscoveryEngineV1.Document

      /// See `DocumentServiceClient.updateDocument`.
      func updateDocument(
        document: Document?,
        updateMask: GoogleCloudWkt.FieldMask?,
      ) async throws -> GoogleCloudDiscoveryEngineV1.Document

      /// See `DocumentServiceClient.deleteDocument`.
      func deleteDocument(request: DeleteDocumentRequest) async throws

      /// See `DocumentServiceClient.deleteDocument`.
      func deleteDocument(
        name: Swift.String,
      ) async throws

      /// See `DocumentServiceClient.importDocuments`.
      func importDocuments(request: ImportDocumentsRequest) async throws
        -> GoogleLongRunning.Operation

      /// See `DocumentServiceClient.importDocuments`.
      func importDocuments(withPolling: ImportDocumentsRequest) async throws -> any GoogleCloudGax
        .PollableOperation<ImportDocumentsResponse>

      /// See `DocumentServiceClient.purgeDocuments`.
      func purgeDocuments(request: PurgeDocumentsRequest) async throws
        -> GoogleLongRunning.Operation

      /// See `DocumentServiceClient.purgeDocuments`.
      func purgeDocuments(withPolling: PurgeDocumentsRequest) async throws -> any GoogleCloudGax
        .PollableOperation<PurgeDocumentsResponse>

      /// See `DocumentServiceClient.batchGetDocumentsMetadata`.
      func batchGetDocumentsMetadata(request: BatchGetDocumentsMetadataRequest) async throws
        -> GoogleCloudDiscoveryEngineV1.BatchGetDocumentsMetadataResponse

      /// See `DocumentServiceClient.batchGetDocumentsMetadata`.
      func batchGetDocumentsMetadata(
        parent: Swift.String,
      ) async throws -> GoogleCloudDiscoveryEngineV1.BatchGetDocumentsMetadataResponse

      /// See `DocumentServiceClient.listOperations`.
      func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
        -> GoogleLongRunning.ListOperationsResponse

      /// See `DocumentServiceClient.listOperations`.
      func listOperations(
        byItem: GoogleLongRunning.ListOperationsRequest
      ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

      /// See `DocumentServiceClient.listOperations`.
      func listOperations(
        name: Swift.String,
        filter: Swift.String,
      ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

      /// See `DocumentServiceClient.cancelOperation`.
      func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

      /// See `DocumentServiceClient.cancelOperation`.
      func cancelOperation(
        name: Swift.String,
      ) async throws

      /// See `DocumentServiceClient.getDocument`.
      func getDocument(
        request: GetDocumentRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryEngineV1.Document

      /// See `DocumentServiceClient.listDocuments`.
      func listDocuments(
        request: ListDocumentsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryEngineV1.ListDocumentsResponse

      /// See `DocumentServiceClient.listDocuments`.
      func listDocuments(
        byItem: ListDocumentsRequest, options: GoogleCloudGax.RequestOptions
      ) throws -> any AsyncSequence<Document, Swift.Error>

      /// See `DocumentServiceClient.createDocument`.
      func createDocument(
        request: CreateDocumentRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryEngineV1.Document

      /// See `DocumentServiceClient.updateDocument`.
      func updateDocument(
        request: UpdateDocumentRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryEngineV1.Document

      /// See `DocumentServiceClient.deleteDocument`.
      func deleteDocument(
        request: DeleteDocumentRequest, options: GoogleCloudGax.RequestOptions
      ) async throws

      /// See `DocumentServiceClient.importDocuments`.
      func importDocuments(
        request: ImportDocumentsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      /// See `DocumentServiceClient.importDocuments`.
      func importDocuments(
        withPolling: ImportDocumentsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> any GoogleCloudGax.PollableOperation<ImportDocumentsResponse>

      /// See `DocumentServiceClient.purgeDocuments`.
      func purgeDocuments(
        request: PurgeDocumentsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      /// See `DocumentServiceClient.purgeDocuments`.
      func purgeDocuments(
        withPolling: PurgeDocumentsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> any GoogleCloudGax.PollableOperation<PurgeDocumentsResponse>

      /// See `DocumentServiceClient.batchGetDocumentsMetadata`.
      func batchGetDocumentsMetadata(
        request: BatchGetDocumentsMetadataRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryEngineV1.BatchGetDocumentsMetadataResponse

      /// See `DocumentServiceClient.listOperations`.
      func listOperations(
        request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.ListOperationsResponse

      /// See `DocumentServiceClient.listOperations`.
      func listOperations(
        byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
      ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

      /// See `DocumentServiceClient.cancelOperation`.
      func cancelOperation(
        request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws
    }
  }

  // Default implementations
  extension Clients.DocumentServiceProtocol {
    public func getDocument(request: GetDocumentRequest) async throws
      -> GoogleCloudDiscoveryEngineV1.Document
    {
      try await self.getDocument(request: request, options: .init())
    }

    public func getDocument(
      request: GetDocumentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDiscoveryEngineV1.Document {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func getDocument(
      name: Swift.String,
    ) async throws -> GoogleCloudDiscoveryEngineV1.Document {
      let request = GetDocumentRequest().with {
        $0.name = name
      }
      return try await self.getDocument(request: request)
    }

    public func listDocuments(request: ListDocumentsRequest) async throws
      -> GoogleCloudDiscoveryEngineV1.ListDocumentsResponse
    {
      try await self.listDocuments(request: request, options: .init())
    }

    public func listDocuments(
      request: ListDocumentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDiscoveryEngineV1.ListDocumentsResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func listDocuments(
      byItem: ListDocumentsRequest
    ) throws -> any AsyncSequence<Document, Swift.Error> {
      try self.listDocuments(byItem: byItem, options: .init())
    }

    public func listDocuments(
      byItem: ListDocumentsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Document, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws -> GoogleCloudDiscoveryEngineV1.ListDocumentsResponse in
        throw GoogleCloudGax.RequestError.unimplemented
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func listDocuments(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Document, Swift.Error> {
      let request = ListDocumentsRequest().with {
        $0.parent = parent
      }
      return try self.listDocuments(byItem: request)
    }

    public func createDocument(request: CreateDocumentRequest) async throws
      -> GoogleCloudDiscoveryEngineV1.Document
    {
      try await self.createDocument(request: request, options: .init())
    }

    public func createDocument(
      request: CreateDocumentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDiscoveryEngineV1.Document {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func createDocument(
      parent: Swift.String,
      document: Document?,
      documentId: Swift.String,
    ) async throws -> GoogleCloudDiscoveryEngineV1.Document {
      let request = CreateDocumentRequest().with {
        $0.parent = parent
        $0.document = document
        $0.documentId = documentId
      }
      return try await self.createDocument(request: request)
    }

    public func updateDocument(request: UpdateDocumentRequest) async throws
      -> GoogleCloudDiscoveryEngineV1.Document
    {
      try await self.updateDocument(request: request, options: .init())
    }

    public func updateDocument(
      request: UpdateDocumentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDiscoveryEngineV1.Document {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func updateDocument(
      document: Document?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> GoogleCloudDiscoveryEngineV1.Document {
      let request = UpdateDocumentRequest().with {
        $0.document = document
        $0.updateMask = updateMask
      }
      return try await self.updateDocument(request: request)
    }

    public func deleteDocument(request: DeleteDocumentRequest) async throws {
      try await self.deleteDocument(request: request, options: .init())
    }

    public func deleteDocument(
      request: DeleteDocumentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func deleteDocument(
      name: Swift.String,
    ) async throws {
      let request = DeleteDocumentRequest().with {
        $0.name = name
      }
      try await self.deleteDocument(request: request)
    }

    public func importDocuments(request: ImportDocumentsRequest) async throws
      -> GoogleLongRunning.Operation
    {
      try await self.importDocuments(request: request, options: .init())
    }

    public func importDocuments(
      request: ImportDocumentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func importDocuments(withPolling: ImportDocumentsRequest) async throws
      -> any GoogleCloudGax.PollableOperation<ImportDocumentsResponse>
    {
      try await self.importDocuments(withPolling: withPolling, options: .init())
    }

    public func importDocuments(
      withPolling: ImportDocumentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<ImportDocumentsResponse> {
      let poll = {
        () async throws -> GoogleCloudGax._PollableOperationImpl<ImportDocumentsResponse>.State in
        throw GoogleCloudGax.RequestError.unimplemented
      }
      return GoogleCloudGax._PollableOperationImpl(
        initialState: .init(done: false, result: nil), poll: poll)
    }

    public func purgeDocuments(request: PurgeDocumentsRequest) async throws
      -> GoogleLongRunning.Operation
    {
      try await self.purgeDocuments(request: request, options: .init())
    }

    public func purgeDocuments(
      request: PurgeDocumentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func purgeDocuments(withPolling: PurgeDocumentsRequest) async throws
      -> any GoogleCloudGax.PollableOperation<PurgeDocumentsResponse>
    {
      try await self.purgeDocuments(withPolling: withPolling, options: .init())
    }

    public func purgeDocuments(
      withPolling: PurgeDocumentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<PurgeDocumentsResponse> {
      let poll = {
        () async throws -> GoogleCloudGax._PollableOperationImpl<PurgeDocumentsResponse>.State in
        throw GoogleCloudGax.RequestError.unimplemented
      }
      return GoogleCloudGax._PollableOperationImpl(
        initialState: .init(done: false, result: nil), poll: poll)
    }

    public func batchGetDocumentsMetadata(request: BatchGetDocumentsMetadataRequest) async throws
      -> GoogleCloudDiscoveryEngineV1.BatchGetDocumentsMetadataResponse
    {
      try await self.batchGetDocumentsMetadata(request: request, options: .init())
    }

    public func batchGetDocumentsMetadata(
      request: BatchGetDocumentsMetadataRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDiscoveryEngineV1.BatchGetDocumentsMetadataResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func batchGetDocumentsMetadata(
      parent: Swift.String,
    ) async throws -> GoogleCloudDiscoveryEngineV1.BatchGetDocumentsMetadataResponse {
      let request = BatchGetDocumentsMetadataRequest().with {
        $0.parent = parent
      }
      return try await self.batchGetDocumentsMetadata(request: request)
    }

    public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse
    {
      try await self.listOperations(request: request, options: .init())
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
      try self.listOperations(byItem: byItem, options: .init())
    }

    public func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
        throw GoogleCloudGax.RequestError.unimplemented
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
      let request = GoogleLongRunning.ListOperationsRequest().with {
        $0.name = name
        $0.filter = filter
      }
      return try self.listOperations(byItem: request)
    }

    public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
      -> GoogleLongRunning.Operation
    {
      try await self.getOperation(request: request, options: .init())
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func getOperation(
      name: Swift.String,
    ) async throws -> GoogleLongRunning.Operation {
      let request = GoogleLongRunning.GetOperationRequest().with {
        $0.name = name
      }
      return try await self.getOperation(request: request)
    }

    public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
      try await self.cancelOperation(request: request, options: .init())
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func cancelOperation(
      name: Swift.String,
    ) async throws {
      let request = GoogleLongRunning.CancelOperationRequest().with {
        $0.name = name
      }
      try await self.cancelOperation(request: request)
    }
  }
#endif
