// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if GroundedGenerationService
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  import GoogleLongRunning
  import GoogleWKT
  @_spi(GoogleCloudInternal) import GoogleGax

  extension Clients {
    final class GroundedGenerationServiceTransport: GroundedGenerationServiceStub {
      let inner: GoogleGax._HTTPClient

      public init(_ options: GoogleGax.ClientOptions = .init()) throws {
        self.inner = try GoogleGax._HTTPClient(
          from: options,
          withDefaultEndpoint: "https://discoveryengine.googleapis.com",
        )
      }

      public func generateGroundedContent(
        request: GenerateGroundedContentRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryEngineV1.GenerateGroundedContentResponse {
        let (path, query, configure, omitted) = try {
          () throws -> (
            Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void,
            [Swift.String]
          ) in
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.location as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                ],
                fieldName: "location")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0):generateGroundedContent"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["location"])
          }
          var paths: [GoogleGax.PathMismatch] = []
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.location as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              ],
              fieldName: "location",
              expecting: "projects/*/locations/*"
            )
            paths.append(builder.build())
          }
          throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
        }()
        var req = try await self.inner.newRequest(
          percentEncodedPath: path, query: query, options: options)
        configure(&req)
        req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
        try req.setBody(json: request, omitting: omitted)
        return try await req.rpc(
          GoogleCloudDiscoveryEngineV1.GenerateGroundedContentResponse.self,
          timeout: options.attemptTimeout
        ).get()
      }

      public func checkGrounding(
        request: CheckGroundingRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryEngineV1.CheckGroundingResponse {
        let (path, query, configure, omitted) = try {
          () throws -> (
            Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void,
            [Swift.String]
          ) in
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.groundingConfig as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/groundingConfigs/"), .singleWildcard,
                ],
                fieldName: "grounding_config")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0):check"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["groundingConfig"])
          }
          var paths: [GoogleGax.PathMismatch] = []
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.groundingConfig as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/groundingConfigs/"), .singleWildcard,
              ],
              fieldName: "grounding_config",
              expecting: "projects/*/locations/*/groundingConfigs/*"
            )
            paths.append(builder.build())
          }
          throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
        }()
        var req = try await self.inner.newRequest(
          percentEncodedPath: path, query: query, options: options)
        configure(&req)
        req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
        try req.setBody(json: request, omitting: omitted)
        return try await req.rpc(
          GoogleCloudDiscoveryEngineV1.CheckGroundingResponse.self, timeout: options.attemptTimeout
        ).get()
      }

      public func listOperations(
        request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.ListOperationsResponse {
        let (path, query, configure) = try {
          () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void)
          in
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [.literal("projects/"), .singleWildcard],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/operations"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            query.append(
              contentsOf: try encoder.encode(
                request.returnPartialSuccess, prefix: "returnPartialSuccess"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/dataConnector"),
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/operations"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            query.append(
              contentsOf: try encoder.encode(
                request.returnPartialSuccess, prefix: "returnPartialSuccess"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                  .singleWildcard, .literal("/branches/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/operations"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            query.append(
              contentsOf: try encoder.encode(
                request.returnPartialSuccess, prefix: "returnPartialSuccess"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                  .singleWildcard, .literal("/models/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/operations"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            query.append(
              contentsOf: try encoder.encode(
                request.returnPartialSuccess, prefix: "returnPartialSuccess"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                  .singleWildcard, .literal("/schemas/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/operations"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            query.append(
              contentsOf: try encoder.encode(
                request.returnPartialSuccess, prefix: "returnPartialSuccess"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                  .singleWildcard, .literal("/siteSearchEngine/targetSites"),
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/operations"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            query.append(
              contentsOf: try encoder.encode(
                request.returnPartialSuccess, prefix: "returnPartialSuccess"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                  .singleWildcard, .literal("/siteSearchEngine"),
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/operations"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            query.append(
              contentsOf: try encoder.encode(
                request.returnPartialSuccess, prefix: "returnPartialSuccess"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                  .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/operations"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            query.append(
              contentsOf: try encoder.encode(
                request.returnPartialSuccess, prefix: "returnPartialSuccess"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/engines/"),
                  .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/operations"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            query.append(
              contentsOf: try encoder.encode(
                request.returnPartialSuccess, prefix: "returnPartialSuccess"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/operations"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            query.append(
              contentsOf: try encoder.encode(
                request.returnPartialSuccess, prefix: "returnPartialSuccess"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/dataStores/"), .singleWildcard, .literal("/branches/"),
                  .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/operations"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            query.append(
              contentsOf: try encoder.encode(
                request.returnPartialSuccess, prefix: "returnPartialSuccess"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/dataStores/"), .singleWildcard, .literal("/models/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/operations"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            query.append(
              contentsOf: try encoder.encode(
                request.returnPartialSuccess, prefix: "returnPartialSuccess"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/dataStores/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/operations"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            query.append(
              contentsOf: try encoder.encode(
                request.returnPartialSuccess, prefix: "returnPartialSuccess"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/identityMappingStores/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/operations"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            query.append(
              contentsOf: try encoder.encode(
                request.returnPartialSuccess, prefix: "returnPartialSuccess"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/operations"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            query.append(
              contentsOf: try encoder.encode(
                request.returnPartialSuccess, prefix: "returnPartialSuccess"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [.literal("projects/"), .singleWildcard],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)/operations"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            query.append(
              contentsOf: try encoder.encode(
                request.returnPartialSuccess, prefix: "returnPartialSuccess"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          var paths: [GoogleGax.PathMismatch] = []
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [.literal("projects/"), .singleWildcard],
              fieldName: "name",
              expecting: "projects/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/dataConnector"),
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/collections/*/dataConnector"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                .singleWildcard, .literal("/branches/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/collections/*/dataStores/*/branches/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                .singleWildcard, .literal("/models/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/collections/*/dataStores/*/models/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                .singleWildcard, .literal("/schemas/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/collections/*/dataStores/*/schemas/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                .singleWildcard, .literal("/siteSearchEngine/targetSites"),
              ],
              fieldName: "name",
              expecting:
                "projects/*/locations/*/collections/*/dataStores/*/siteSearchEngine/targetSites"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                .singleWildcard, .literal("/siteSearchEngine"),
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/collections/*/dataStores/*/siteSearchEngine"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/collections/*/dataStores/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/engines/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/collections/*/engines/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/collections/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/dataStores/"), .singleWildcard, .literal("/branches/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/dataStores/*/branches/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/dataStores/"), .singleWildcard, .literal("/models/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/dataStores/*/models/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/dataStores/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/dataStores/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/identityMappingStores/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/identityMappingStores/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [.literal("projects/"), .singleWildcard],
              fieldName: "name",
              expecting: "projects/*"
            )
            paths.append(builder.build())
          }
          throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
        }()
        var req = try await self.inner.newRequest(
          percentEncodedPath: path, query: query, options: options)
        configure(&req)
        req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
        return try await req.rpc(
          GoogleLongRunning.ListOperationsResponse.self, timeout: options.attemptTimeout
        ).get()
      }

      public func getOperation(
        request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation {
        let (path, query, configure) = try {
          () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void)
          in
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/operations/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard,
                  .literal("/dataConnector/operations/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                  .singleWildcard, .literal("/branches/"), .singleWildcard,
                  .literal("/operations/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                  .singleWildcard, .literal("/models/"), .singleWildcard, .literal("/operations/"),
                  .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                  .singleWildcard, .literal("/operations/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                  .singleWildcard, .literal("/schemas/"), .singleWildcard, .literal("/operations/"),
                  .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                  .singleWildcard, .literal("/siteSearchEngine/operations/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                  .singleWildcard, .literal("/siteSearchEngine/targetSites/operations/"),
                  .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/engines/"),
                  .singleWildcard, .literal("/operations/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/operations/"),
                  .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/dataStores/"), .singleWildcard, .literal("/branches/"),
                  .singleWildcard, .literal("/operations/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/dataStores/"), .singleWildcard, .literal("/models/"), .singleWildcard,
                  .literal("/operations/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/dataStores/"), .singleWildcard, .literal("/operations/"),
                  .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/identityMappingStores/"), .singleWildcard, .literal("/operations/"),
                  .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/operations/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/operations/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          var paths: [GoogleGax.PathMismatch] = []
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/operations/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/dataConnector/operations/"),
                .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/collections/*/dataConnector/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                .singleWildcard, .literal("/branches/"), .singleWildcard, .literal("/operations/"),
                .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/collections/*/dataStores/*/branches/*/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                .singleWildcard, .literal("/models/"), .singleWildcard, .literal("/operations/"),
                .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/collections/*/dataStores/*/models/*/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                .singleWildcard, .literal("/operations/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/collections/*/dataStores/*/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                .singleWildcard, .literal("/schemas/"), .singleWildcard, .literal("/operations/"),
                .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/collections/*/dataStores/*/schemas/*/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                .singleWildcard, .literal("/siteSearchEngine/operations/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting:
                "projects/*/locations/*/collections/*/dataStores/*/siteSearchEngine/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                .singleWildcard, .literal("/siteSearchEngine/targetSites/operations/"),
                .singleWildcard,
              ],
              fieldName: "name",
              expecting:
                "projects/*/locations/*/collections/*/dataStores/*/siteSearchEngine/targetSites/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/engines/"), .singleWildcard,
                .literal("/operations/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/collections/*/engines/*/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/operations/"),
                .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/collections/*/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/dataStores/"), .singleWildcard, .literal("/branches/"), .singleWildcard,
                .literal("/operations/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/dataStores/*/branches/*/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/dataStores/"), .singleWildcard, .literal("/models/"), .singleWildcard,
                .literal("/operations/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/dataStores/*/models/*/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/dataStores/"), .singleWildcard, .literal("/operations/"),
                .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/dataStores/*/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/identityMappingStores/"), .singleWildcard, .literal("/operations/"),
                .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/identityMappingStores/*/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/operations/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/operations/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/operations/*"
            )
            paths.append(builder.build())
          }
          throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
        }()
        var req = try await self.inner.newRequest(
          percentEncodedPath: path, query: query, options: options)
        configure(&req)
        req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
        return try await req.rpc(
          GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
        ).get()
      }

      public func cancelOperation(
        request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
      ) async throws {
        let (path, query, configure, omitted) = try {
          () throws -> (
            Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void,
            [Swift.String]
          ) in
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/operations/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0):cancel"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["name"])
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                  .singleWildcard, .literal("/branches/"), .singleWildcard,
                  .literal("/operations/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0):cancel"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["name"])
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/collections/"), .singleWildcard, .literal("/engines/"),
                  .singleWildcard, .literal("/operations/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0):cancel"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["name"])
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/dataStores/"), .singleWildcard, .literal("/branches/"),
                  .singleWildcard, .literal("/operations/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v1/\(pathVariable0):cancel"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["name"])
          }
          var paths: [GoogleGax.PathMismatch] = []
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/operations/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/dataStores/"),
                .singleWildcard, .literal("/branches/"), .singleWildcard, .literal("/operations/"),
                .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/collections/*/dataStores/*/branches/*/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/collections/"), .singleWildcard, .literal("/engines/"), .singleWildcard,
                .literal("/operations/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/collections/*/engines/*/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/dataStores/"), .singleWildcard, .literal("/branches/"), .singleWildcard,
                .literal("/operations/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/dataStores/*/branches/*/operations/*"
            )
            paths.append(builder.build())
          }
          throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
        }()
        var req = try await self.inner.newRequest(
          percentEncodedPath: path, query: query, options: options)
        configure(&req)
        req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
        try req.setBody(json: request, omitting: omitted)
        _ = try await req.rpc(
          GoogleWKT.WKTEmpty.self, timeout: options.attemptTimeout
        ).get()
      }
    }
  }
#endif
