// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if UserEventService
  import Foundation
  public import GoogleRpc
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// Response of the ImportUserEventsRequest. If the long running
  /// operation was successful, then this message is returned by the
  /// google.longrunning.Operations.response field if the operation was successful.
  public struct ImportUserEventsResponse: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// A sample of errors encountered while processing the request.
    public var errorSamples: [GoogleRpc.Status] = []

    /// Echoes the destination for the complete errors if this field was set in
    /// the request.
    public var errorConfig: ImportErrorConfig? = nil

    /// Count of user events imported with complete existing Documents.
    public var joinedEventsCount: Swift.Int64 = Swift.Int64()

    /// Count of user events imported, but with Document information not found
    /// in the existing Branch.
    public var unjoinedEventsCount: Swift.Int64 = Swift.Int64()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ImportUserEventsResponse`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ImportUserEventsResponse().with { $0.errorSamples = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let errorSamples = CodingKeys(stringValue: "errorSamples")
      static let errorConfig = CodingKeys(stringValue: "errorConfig")
      static let joinedEventsCount = CodingKeys(stringValue: "joinedEventsCount")
      static let unjoinedEventsCount = CodingKeys(stringValue: "unjoinedEventsCount")

      static let _knownKeys: Set<Swift.String> = [
        "errorSamples",
        "errorConfig",
        "joinedEventsCount",
        "unjoinedEventsCount",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([GoogleRpc.Status].self, forKey: .errorSamples) {
        self.errorSamples = value
      }
      self.errorConfig = try container.decodeIfPresent(ImportErrorConfig.self, forKey: .errorConfig)
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .joinedEventsCount) {
        self.joinedEventsCount = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .unjoinedEventsCount) {
        self.unjoinedEventsCount = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.errorSamples, forKey: .errorSamples)
      try container.encodeIfPresent(self.errorConfig, forKey: .errorConfig)
      try container.encode(self.joinedEventsCount, forKey: .joinedEventsCount)
      try container.encode(self.unjoinedEventsCount, forKey: .unjoinedEventsCount)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.discoveryengine.v1.ImportUserEventsResponse"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
