// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if UserEventService
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWkt

  /// Request message for the ImportUserEvents request.
  public struct ImportUserEventsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. Parent DataStore resource name, of the form
    /// `projects/{project}/locations/{location}/collections/{collection}/dataStores/{data_store}`
    public var parent: Swift.String = Swift.String()

    /// The desired location of errors incurred during the Import. Cannot be set
    /// for inline user event imports.
    public var errorConfig: ImportErrorConfig? = nil

    /// Required - The desired input source of the user event data.
    public var source: OneOf_Source? = nil

    /// Initialize a new instance of `ImportUserEventsRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ImportUserEventsRequest().with { $0.inlineSource = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case inlineSource = "inlineSource"
      case gcsSource = "gcsSource"
      case bigquerySource = "bigquerySource"
      case parent = "parent"
      case errorConfig = "errorConfig"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.parent = try container.decode(Swift.String.self, forKey: .parent)
      self.errorConfig = try container.decodeIfPresent(ImportErrorConfig.self, forKey: .errorConfig)

      var source: OneOf_Source? = nil
      let sourceCheckAndSet = {
        if source != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'source'"))
        }
        source = $0
      }
      if let inlineSource = try container.decodeIfPresent(
        ImportUserEventsRequest.InlineSource?.self, forKey: .inlineSource)
      {
        try sourceCheckAndSet(.inlineSource(inlineSource))
      }
      if let gcsSource = try container.decodeIfPresent(GcsSource?.self, forKey: .gcsSource) {
        try sourceCheckAndSet(.gcsSource(gcsSource))
      }
      if let bigquerySource = try container.decodeIfPresent(
        BigQuerySource?.self, forKey: .bigquerySource)
      {
        try sourceCheckAndSet(.bigquerySource(bigquerySource))
      }
      self.source = source
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.parent, forKey: .parent)
      try container.encode(self.errorConfig, forKey: .errorConfig)

      if let choice = self.source {
        switch choice {
        case .inlineSource(let value):
          try container.encode(value, forKey: .inlineSource)
        case .gcsSource(let value):
          try container.encode(value, forKey: .gcsSource)
        case .bigquerySource(let value):
          try container.encode(value, forKey: .bigquerySource)
        }
      }
    }

    /// The inline source for the input config for ImportUserEvents method.
    public struct InlineSource: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Required. A list of user events to import. Recommended max of 10k items.
      public var userEvents: [UserEvent] = []

      /// Initialize a new instance of `InlineSource`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = InlineSource().with { $0.userEvents = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.discoveryengine.v1.ImportUserEventsRequest.InlineSource"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Required - The desired input source of the user event data.
    public enum OneOf_Source: Codable, Equatable, Sendable {
      /// The Inline source for the input content for UserEvents.
      indirect case inlineSource(ImportUserEventsRequest.InlineSource?)
      /// Cloud Storage location for the input content.
      indirect case gcsSource(GcsSource?)
      /// BigQuery input source.
      indirect case bigquerySource(BigQuerySource?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.discoveryengine.v1.ImportUserEventsRequest"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
