// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if ConversationalSearchService
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleWKT

  /// Request for ListConversations method.
  public struct ListConversationsRequest: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. The data store resource name. Format:
    /// `projects/{project}/locations/{location}/collections/{collection}/dataStores/{data_store_id}`
    public var parent: Swift.String = Swift.String()

    /// Maximum number of results to return. If unspecified, defaults
    /// to 50. Max allowed value is 1000.
    public var pageSize: Swift.Int32 = Swift.Int32()

    /// A page token, received from a previous `ListConversations` call.
    /// Provide this to retrieve the subsequent page.
    public var pageToken: Swift.String = Swift.String()

    /// A filter to apply on the list results. The supported features are:
    /// user_pseudo_id, state.
    ///
    /// Example:
    /// "user_pseudo_id = some_id"
    public var filter: Swift.String = Swift.String()

    /// A comma-separated list of fields to order by, sorted in ascending order.
    /// Use "desc" after a field name for descending.
    /// Supported fields:
    ///   * `update_time`
    ///   * `create_time`
    ///   * `conversation_name`
    ///
    /// Example:
    /// "update_time desc"
    /// "create_time"
    public var orderBy: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ListConversationsRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ListConversationsRequest().with { $0.parent = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let parent = CodingKeys(stringValue: "parent")
      static let pageSize = CodingKeys(stringValue: "pageSize")
      static let pageToken = CodingKeys(stringValue: "pageToken")
      static let filter = CodingKeys(stringValue: "filter")
      static let orderBy = CodingKeys(stringValue: "orderBy")

      static let _knownKeys: Set<Swift.String> = [
        "parent",
        "pageSize",
        "pageToken",
        "filter",
        "orderBy",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
        self.parent = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .pageSize) {
        self.pageSize = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pageToken) {
        self.pageToken = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .filter) {
        self.filter = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .orderBy) {
        self.orderBy = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.parent, forKey: .parent)
      try container.encode(self.pageSize, forKey: .pageSize)
      try container.encode(self.pageToken, forKey: .pageToken)
      try container.encode(self.filter, forKey: .filter)
      try container.encode(self.orderBy, forKey: .orderBy)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.discoveryengine.v1.ListConversationsRequest"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
