// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if IdentityMappingStoreService
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudGax
  @_spi(GoogleCloudInternal) import GoogleCloudWKT

  /// Response message for
  /// [IdentityMappingStoreService.ListIdentityMappingStores][google.cloud.discoveryengine.v1.IdentityMappingStoreService.ListIdentityMappingStores]
  ///
  /// [google.cloud.discoveryengine.v1.IdentityMappingStoreService.ListIdentityMappingStores]: <doc:IdentityMappingStoreServiceClient/listIdentityMappingStores(request:options:)>
  public struct ListIdentityMappingStoresResponse: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    GoogleCloudGax._PaginatedResponse,
    Sendable
  {
    /// The Identity Mapping Stores.
    public var identityMappingStores: [IdentityMappingStore] = []

    /// A token that can be sent as `page_token` to retrieve the next page. If this
    /// field is omitted, there are no subsequent pages.
    public var nextPageToken: Swift.String = Swift.String()

    /// Initialize a new instance of `ListIdentityMappingStoresResponse`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ListIdentityMappingStoresResponse().with { $0.identityMappingStores = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.discoveryengine.v1.ListIdentityMappingStoresResponse"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }

    public func _getPaginatedItems() -> [IdentityMappingStore] {
      return self.identityMappingStores
    }

    public func _nextPageToken() -> Swift.String {
      return self.nextPageToken
    }
  }
#endif
