// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if ProjectService
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// Metadata and configurations for a Google Cloud project in the service.
  public struct Project: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. Full resource name of the project, for example
    /// `projects/{project}`.
    /// Note that when making requests, project number and project id are both
    /// acceptable, but the server will always respond in project number.
    public var name: Swift.String = Swift.String()

    /// Output only. The timestamp when this project is created.
    public var createTime: GoogleWKT.WKTTimestamp? = nil

    /// Output only. The timestamp when this project is successfully provisioned.
    /// Empty value means this project is still provisioning and is not ready for
    /// use.
    public var provisionCompletionTime: GoogleWKT.WKTTimestamp? = nil

    /// Output only. A map of terms of services. The key is the `id` of
    /// [ServiceTerms][google.cloud.discoveryengine.v1.Project.ServiceTerms].
    ///
    /// [google.cloud.discoveryengine.v1.Project.ServiceTerms]: <doc:Project/ServiceTerms>
    public var serviceTermsMap: [Swift.String: Project.ServiceTerms] = [:]

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Project`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Project().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let name = CodingKeys(stringValue: "name")
      static let createTime = CodingKeys(stringValue: "createTime")
      static let provisionCompletionTime = CodingKeys(stringValue: "provisionCompletionTime")
      static let serviceTermsMap = CodingKeys(stringValue: "serviceTermsMap")

      static let _knownKeys: Set<Swift.String> = [
        "name",
        "createTime",
        "provisionCompletionTime",
        "serviceTermsMap",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
        self.name = value
      }
      self.createTime = try container.decodeIfPresent(
        GoogleWKT.WKTTimestamp.self, forKey: .createTime)
      self.provisionCompletionTime = try container.decodeIfPresent(
        GoogleWKT.WKTTimestamp.self, forKey: .provisionCompletionTime)
      if let value = try container.decodeIfPresent(
        [Swift.String: Project.ServiceTerms].self, forKey: .serviceTermsMap)
      {
        self.serviceTermsMap = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.name, forKey: .name)
      try container.encodeIfPresent(self.createTime, forKey: .createTime)
      try container.encodeIfPresent(self.provisionCompletionTime, forKey: .provisionCompletionTime)
      try container.encode(self.serviceTermsMap, forKey: .serviceTermsMap)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Metadata about the terms of service.
    public struct ServiceTerms: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// The unique identifier of this terms of service.
      /// Available terms:
      ///
      /// * `GA_DATA_USE_TERMS`: [Terms for data
      /// use](https://cloud.google.com/retail/data-use-terms). When using this as
      /// `id`, the acceptable
      /// [version][google.cloud.discoveryengine.v1.Project.ServiceTerms.version]
      /// to provide is `2022-11-23`.
      ///
      /// [google.cloud.discoveryengine.v1.Project.ServiceTerms.version]: <doc:Project/ServiceTerms/version>
      public var id: Swift.String = Swift.String()

      /// The version string of the terms of service.
      /// For acceptable values, see the comments for
      /// [id][google.cloud.discoveryengine.v1.Project.ServiceTerms.id] above.
      ///
      /// [google.cloud.discoveryengine.v1.Project.ServiceTerms.id]: <doc:Project/ServiceTerms/id>
      public var version: Swift.String = Swift.String()

      /// Whether the project has accepted/rejected the service terms or it is
      /// still pending.
      public var state: Project.ServiceTerms.State = Project.ServiceTerms.State()

      /// The last time when the project agreed to the terms of service.
      public var acceptTime: GoogleWKT.WKTTimestamp? = nil

      /// The last time when the project declined or revoked the agreement to terms
      /// of service.
      public var declineTime: GoogleWKT.WKTTimestamp? = nil

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `ServiceTerms`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = ServiceTerms().with { $0.id = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let id = CodingKeys(stringValue: "id")
        static let version = CodingKeys(stringValue: "version")
        static let state = CodingKeys(stringValue: "state")
        static let acceptTime = CodingKeys(stringValue: "acceptTime")
        static let declineTime = CodingKeys(stringValue: "declineTime")

        static let _knownKeys: Set<Swift.String> = [
          "id",
          "version",
          "state",
          "acceptTime",
          "declineTime",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .id) {
          self.id = value
        }
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .version) {
          self.version = value
        }
        if let value = try container.decodeIfPresent(
          Project.ServiceTerms.State.self, forKey: .state)
        {
          self.state = value
        }
        self.acceptTime = try container.decodeIfPresent(
          GoogleWKT.WKTTimestamp.self, forKey: .acceptTime)
        self.declineTime = try container.decodeIfPresent(
          GoogleWKT.WKTTimestamp.self, forKey: .declineTime)
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.id, forKey: .id)
        try container.encode(self.version, forKey: .version)
        try container.encode(self.state, forKey: .state)
        try container.encodeIfPresent(self.acceptTime, forKey: .acceptTime)
        try container.encodeIfPresent(self.declineTime, forKey: .declineTime)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      /// The agreement states this terms of service.
      ///
      /// - Note: Adding cases to this enumeration is not considered a breaking change.
      ///   Always include an `@unknown default:` case when switching over this type.
      ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
      ///   expecting specific values to remain unparsed; future releases may promote
      ///   them to named cases.
      public enum State: Codable, Equatable, Hashable, Sendable {
        /// The default value of the enum. This value is not actually used.
        case unspecified
        /// The project has given consent to the terms of service.
        case termsAccepted
        /// The project is pending to review and accept the terms of service.
        case termsPending
        /// The project has declined or revoked the agreement to terms of service.
        case termsDeclined
        /// Encodes an unknown integer value.
        ///
        /// The most common cause for an unknown value is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        ///
        /// - Warning: Do not pattern-match specific integer values in this case;
        ///   future releases may promote them to named enum cases.
        case unknownIntValue(Int)
        /// Encodes an unknown string value.
        ///
        /// The most common cause for an unknown value is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        ///
        /// - Warning: Do not pattern-match specific string literals in this case;
        ///   future releases may promote them to named enum cases.
        case unknownStringValue(String)

        public init() {
          self = .unspecified
        }

        /// Returns the integer value associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown string value, this returns `nil`.
        public var intValue: Int? {
          switch self {
          case .unspecified: return 0
          case .termsAccepted: return 1
          case .termsPending: return 2
          case .termsDeclined: return 3
          case .unknownIntValue(let v): return v
          case .unknownStringValue: return nil
          }
        }

        /// Returns the string value (or name) associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
        public var stringValue: Swift.String? {
          switch self {
          case .unspecified: return "STATE_UNSPECIFIED"
          case .termsAccepted: return "TERMS_ACCEPTED"
          case .termsPending: return "TERMS_PENDING"
          case .termsDeclined: return "TERMS_DECLINED"
          case .unknownIntValue: return nil
          case .unknownStringValue(let v): return v
          }
        }

        /// Initialize from a string value.
        ///
        /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
        public init(stringValue: Swift.String) {
          switch stringValue {
          case "STATE_UNSPECIFIED": self = .unspecified
          case "TERMS_ACCEPTED": self = .termsAccepted
          case "TERMS_PENDING": self = .termsPending
          case "TERMS_DECLINED": self = .termsDeclined
          default: self = .unknownStringValue(stringValue)
          }
        }

        /// Initialize from an integer value.
        ///
        /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
        public init(intValue: Int) {
          switch intValue {
          case 0: self = .unspecified
          case 1: self = .termsAccepted
          case 2: self = .termsPending
          case 3: self = .termsDeclined
          default: self = .unknownIntValue(intValue)
          }
        }

        public init(from decoder: Decoder) throws {
          let container = try decoder.singleValueContainer()
          if let v = try? container.decode(Int.self) {
            self.init(intValue: v)
            return
          }
          if let s = try? container.decode(String.self) {
            if let v = Int(s) {
              self.init(intValue: v)
            } else {
              self.init(stringValue: s)
            }
            return
          }
          throw DecodingError.dataCorruptedError(
            in: container, debugDescription: "Expected enum value, must be integer or string.")
        }

        public func encode(to encoder: Encoder) throws {
          var container = encoder.singleValueContainer()
          switch self {
          case .unspecified: return try container.encode("STATE_UNSPECIFIED")
          case .termsAccepted: return try container.encode("TERMS_ACCEPTED")
          case .termsPending: return try container.encode("TERMS_PENDING")
          case .termsDeclined: return try container.encode("TERMS_DECLINED")
          case .unknownIntValue(let v): return try container.encode(v)
          case .unknownStringValue(let v): return try container.encode(v)
          }
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.discoveryengine.v1.Project.ServiceTerms"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.discoveryengine.v1.Project"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
