// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if IdentityMappingStoreService
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWkt

  /// Request message for
  /// [IdentityMappingStoreService.PurgeIdentityMappings][google.cloud.discoveryengine.v1.IdentityMappingStoreService.PurgeIdentityMappings]
  ///
  /// [google.cloud.discoveryengine.v1.IdentityMappingStoreService.PurgeIdentityMappings]: <doc:IdentityMappingStoreServiceClient/purgeIdentityMappings(request:options:)>
  public struct PurgeIdentityMappingsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. The name of the Identity Mapping Store to purge Identity Mapping
    /// Entries from. Format:
    /// `projects/{project}/locations/{location}/identityMappingStores/{identityMappingStore}`
    public var identityMappingStore: Swift.String = Swift.String()

    /// Filter matching identity mappings to purge.
    /// The eligible field for filtering is:
    /// * `update_time`: in ISO 8601 "zulu" format.
    /// * `external_id`
    ///
    /// Examples:
    ///
    /// * Deleting all identity mappings updated in a time range:
    ///   `update_time > "2012-04-23T18:25:43.511Z" AND update_time <
    ///   "2012-04-23T18:30:43.511Z"`
    /// * Deleting all identity mappings for a given external_id:
    /// `external_id = "id1"`
    /// * Deleting all identity mappings inside an identity mapping store:
    ///   `*`
    ///
    /// The filtering fields are assumed to have an implicit AND.
    /// Should not be used with source. An error will be thrown, if both are
    /// provided.
    public var filter: Swift.String = Swift.String()

    /// Actually performs the purge. If `force` is set to false, return the
    /// expected purge count without deleting any identity mappings. This field is
    /// only supported for purge with filter. For input source this field is
    /// ignored and data will be purged regardless of the value of this field.
    public var force: Swift.Bool? = nil

    /// The source of the input.
    public var source: OneOf_Source? = nil

    /// Initialize a new instance of `PurgeIdentityMappingsRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PurgeIdentityMappingsRequest().with { $0.inlineSource = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case inlineSource = "inlineSource"
      case identityMappingStore = "identityMappingStore"
      case filter = "filter"
      case force = "force"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.identityMappingStore = try container.decode(
        Swift.String.self, forKey: .identityMappingStore)
      self.filter = try container.decode(Swift.String.self, forKey: .filter)
      self.force = try container.decodeIfPresent(Swift.Bool.self, forKey: .force)

      var source: OneOf_Source? = nil
      let sourceCheckAndSet = {
        if source != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'source'"))
        }
        source = $0
      }
      if let inlineSource = try container.decodeIfPresent(
        PurgeIdentityMappingsRequest.InlineSource?.self, forKey: .inlineSource)
      {
        try sourceCheckAndSet(.inlineSource(inlineSource))
      }
      self.source = source
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.identityMappingStore, forKey: .identityMappingStore)
      try container.encode(self.filter, forKey: .filter)
      try container.encode(self.force, forKey: .force)

      if let choice = self.source {
        switch choice {
        case .inlineSource(let value):
          try container.encode(value, forKey: .inlineSource)
        }
      }
    }

    /// The inline source to purge identity mapping entries from.
    public struct InlineSource: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// A maximum of 10000 entries can be purged at one time
      public var identityMappingEntries: [IdentityMappingEntry] = []

      /// Initialize a new instance of `InlineSource`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = InlineSource().with { $0.identityMappingEntries = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.discoveryengine.v1.PurgeIdentityMappingsRequest.InlineSource"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// The source of the input.
    public enum OneOf_Source: Codable, Equatable, Sendable {
      /// The inline source to purge identity mapping entries from.
      indirect case inlineSource(PurgeIdentityMappingsRequest.InlineSource?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.discoveryengine.v1.PurgeIdentityMappingsRequest"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
