// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if RecommendationService
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWkt

  /// Response message for Recommend method.
  public struct RecommendResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// A list of recommended Documents. The order represents the ranking (from the
    /// most relevant Document to the least).
    public var results: [RecommendResponse.RecommendationResult] = []

    /// A unique attribution token. This should be included in the
    /// [UserEvent][google.cloud.discoveryengine.v1.UserEvent] logs resulting from
    /// this recommendation, which enables accurate attribution of recommendation
    /// model performance.
    ///
    /// [google.cloud.discoveryengine.v1.UserEvent]: <doc:UserEvent>
    public var attributionToken: Swift.String = Swift.String()

    /// IDs of documents in the request that were missing from the default Branch
    /// associated with the requested ServingConfig.
    public var missingIds: [Swift.String] = []

    /// True if
    /// [RecommendRequest.validate_only][google.cloud.discoveryengine.v1.RecommendRequest.validate_only]
    /// was set.
    ///
    /// [google.cloud.discoveryengine.v1.RecommendRequest.validate_only]: <doc:RecommendRequest/validateOnly>
    public var validateOnly: Swift.Bool = Swift.Bool()

    /// Initialize a new instance of `RecommendResponse`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RecommendResponse().with { $0.results = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// RecommendationResult represents a generic recommendation result with
    /// associated metadata.
    public struct RecommendationResult: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Resource ID of the recommended Document.
      public var id: Swift.String = Swift.String()

      /// Set if `returnDocument` is set to true in
      /// [RecommendRequest.params][google.cloud.discoveryengine.v1.RecommendRequest.params].
      ///
      /// [google.cloud.discoveryengine.v1.RecommendRequest.params]: <doc:RecommendRequest/params>
      public var document: Document? = nil

      /// Additional Document metadata or annotations.
      ///
      /// Possible values:
      ///
      /// * `score`: Recommendation score in double value. Is set if
      ///   `returnScore` is set to true in
      ///   [RecommendRequest.params][google.cloud.discoveryengine.v1.RecommendRequest.params].
      ///
      /// [google.cloud.discoveryengine.v1.RecommendRequest.params]: <doc:RecommendRequest/params>
      public var metadata: [Swift.String: GoogleCloudWkt.Value] = [:]

      /// Initialize a new instance of `RecommendationResult`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = RecommendationResult().with { $0.id = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.discoveryengine.v1.RecommendResponse.RecommendationResult"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.discoveryengine.v1.RecommendResponse"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
