// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SiteSearchEngineService
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWKT

  /// Metadata related to the progress of the
  /// [SiteSearchEngineService.RecrawlUris][google.cloud.discoveryengine.v1.SiteSearchEngineService.RecrawlUris]
  /// operation. This will be returned by the google.longrunning.Operation.metadata
  /// field.
  ///
  /// [google.cloud.discoveryengine.v1.SiteSearchEngineService.RecrawlUris]: <doc:SiteSearchEngineServiceClient/recrawlUris(request:options:)>
  public struct RecrawlUrisMetadata: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Operation create time.
    public var createTime: GoogleCloudWKT.Timestamp? = nil

    /// Operation last update time. If the operation is done, this is also the
    /// finish time.
    public var updateTime: GoogleCloudWKT.Timestamp? = nil

    /// Unique URIs in the request that have invalid format. Sample limited to
    /// 1000.
    public var invalidUris: [Swift.String] = []

    /// Total number of unique URIs in the request that have invalid format.
    public var invalidUrisCount: Swift.Int32 = Swift.Int32()

    /// URIs that have no index meta tag. Sample limited to 1000.
    public var noindexUris: [Swift.String] = []

    /// Total number of URIs that have no index meta tag.
    public var noindexUrisCount: Swift.Int32 = Swift.Int32()

    /// Unique URIs in the request that don't match any TargetSite in the
    /// DataStore, only match TargetSites that haven't been fully indexed, or match
    /// a TargetSite with type EXCLUDE. Sample limited to 1000.
    public var urisNotMatchingTargetSites: [Swift.String] = []

    /// Total number of URIs that don't match any TargetSites.
    public var urisNotMatchingTargetSitesCount: Swift.Int32 = Swift.Int32()

    /// Total number of unique URIs in the request that are not in invalid_uris.
    public var validUrisCount: Swift.Int32 = Swift.Int32()

    /// Total number of URIs that have been crawled so far.
    public var successCount: Swift.Int32 = Swift.Int32()

    /// Total number of URIs that have yet to be crawled.
    public var pendingCount: Swift.Int32 = Swift.Int32()

    /// Total number of URIs that were rejected due to insufficient indexing
    /// resources.
    public var quotaExceededCount: Swift.Int32 = Swift.Int32()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `RecrawlUrisMetadata`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RecrawlUrisMetadata().with { $0.createTime = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let createTime = CodingKeys(stringValue: "createTime")
      static let updateTime = CodingKeys(stringValue: "updateTime")
      static let invalidUris = CodingKeys(stringValue: "invalidUris")
      static let invalidUrisCount = CodingKeys(stringValue: "invalidUrisCount")
      static let noindexUris = CodingKeys(stringValue: "noindexUris")
      static let noindexUrisCount = CodingKeys(stringValue: "noindexUrisCount")
      static let urisNotMatchingTargetSites = CodingKeys(stringValue: "urisNotMatchingTargetSites")
      static let urisNotMatchingTargetSitesCount = CodingKeys(
        stringValue: "urisNotMatchingTargetSitesCount")
      static let validUrisCount = CodingKeys(stringValue: "validUrisCount")
      static let successCount = CodingKeys(stringValue: "successCount")
      static let pendingCount = CodingKeys(stringValue: "pendingCount")
      static let quotaExceededCount = CodingKeys(stringValue: "quotaExceededCount")

      static let _knownKeys: Set<Swift.String> = [
        "createTime",
        "updateTime",
        "invalidUris",
        "invalidUrisCount",
        "noindexUris",
        "noindexUrisCount",
        "urisNotMatchingTargetSites",
        "urisNotMatchingTargetSitesCount",
        "validUrisCount",
        "successCount",
        "pendingCount",
        "quotaExceededCount",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.createTime = try container.decodeIfPresent(
        GoogleCloudWKT.Timestamp.self, forKey: .createTime)
      self.updateTime = try container.decodeIfPresent(
        GoogleCloudWKT.Timestamp.self, forKey: .updateTime)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .invalidUris) {
        self.invalidUris = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .invalidUrisCount) {
        self.invalidUrisCount = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .noindexUris) {
        self.noindexUris = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .noindexUrisCount) {
        self.noindexUrisCount = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String].self, forKey: .urisNotMatchingTargetSites)
      {
        self.urisNotMatchingTargetSites = value
      }
      if let value = try container.decodeIfPresent(
        Swift.Int32.self, forKey: .urisNotMatchingTargetSitesCount)
      {
        self.urisNotMatchingTargetSitesCount = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .validUrisCount) {
        self.validUrisCount = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .successCount) {
        self.successCount = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .pendingCount) {
        self.pendingCount = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .quotaExceededCount) {
        self.quotaExceededCount = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.createTime, forKey: .createTime)
      try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
      try container.encode(self.invalidUris, forKey: .invalidUris)
      try container.encode(self.invalidUrisCount, forKey: .invalidUrisCount)
      try container.encode(self.noindexUris, forKey: .noindexUris)
      try container.encode(self.noindexUrisCount, forKey: .noindexUrisCount)
      try container.encode(self.urisNotMatchingTargetSites, forKey: .urisNotMatchingTargetSites)
      try container.encode(
        self.urisNotMatchingTargetSitesCount, forKey: .urisNotMatchingTargetSitesCount)
      try container.encode(self.validUrisCount, forKey: .validUrisCount)
      try container.encode(self.successCount, forKey: .successCount)
      try container.encode(self.pendingCount, forKey: .pendingCount)
      try container.encode(self.quotaExceededCount, forKey: .quotaExceededCount)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.discoveryengine.v1.RecrawlUrisMetadata"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }
#endif
