// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SiteSearchEngineService
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleWKT

  /// Request message for
  /// [SiteSearchEngineService.RecrawlUris][google.cloud.discoveryengine.v1.SiteSearchEngineService.RecrawlUris]
  /// method.
  ///
  /// [google.cloud.discoveryengine.v1.SiteSearchEngineService.RecrawlUris]: <doc:SiteSearchEngineServiceClient/recrawlUris(request:options:)>
  public struct RecrawlUrisRequest: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. Full resource name of the
    /// [SiteSearchEngine][google.cloud.discoveryengine.v1.SiteSearchEngine], such
    /// as `projects/*/locations/*/collections/*/dataStores/*/siteSearchEngine`.
    ///
    /// [google.cloud.discoveryengine.v1.SiteSearchEngine]: <doc:SiteSearchEngine>
    public var siteSearchEngine: Swift.String = Swift.String()

    /// Required. List of URIs to crawl. At most 10K URIs are supported, otherwise
    /// an INVALID_ARGUMENT error is thrown. Each URI should match at least one
    /// [TargetSite][google.cloud.discoveryengine.v1.TargetSite] in
    /// `site_search_engine`.
    ///
    /// [google.cloud.discoveryengine.v1.TargetSite]: <doc:TargetSite>
    public var uris: [Swift.String] = []

    /// Optional. Credential id to use for crawling.
    public var siteCredential: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `RecrawlUrisRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RecrawlUrisRequest().with { $0.siteSearchEngine = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let siteSearchEngine = CodingKeys(stringValue: "siteSearchEngine")
      static let uris = CodingKeys(stringValue: "uris")
      static let siteCredential = CodingKeys(stringValue: "siteCredential")

      static let _knownKeys: Set<Swift.String> = [
        "siteSearchEngine",
        "uris",
        "siteCredential",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .siteSearchEngine) {
        self.siteSearchEngine = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .uris) {
        self.uris = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .siteCredential) {
        self.siteCredential = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.siteSearchEngine, forKey: .siteSearchEngine)
      try container.encode(self.uris, forKey: .uris)
      try container.encode(self.siteCredential, forKey: .siteCredential)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.discoveryengine.v1.RecrawlUrisRequest"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
