// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SchemaService
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  import GoogleCloudWkt
  import GoogleLongRunning
  import GoogleRpc
  @_spi(GoogleCloudInternal) import GoogleCloudGax

  extension Clients {
    final class SchemaServiceTransport: SchemaServiceStub {
      let inner: GoogleCloudGax._HTTPClient

      public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
        self.inner = try GoogleCloudGax._HTTPClient(
          from: options,
          withDefaultEndpoint: "https://discoveryengine.googleapis.com",
        )
      }

      public func getSchema(
        request: GetSchemaRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryEngineV1.Schema {
        let path = try { () throws -> Swift.String in
          guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
            throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
          }
          return "/v1/\(pathVariable0)"
        }()
        let query = [
          URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
        ]
        var req = try await self.inner.newRequest(path: path, query: query)
        req.setMethod(.GET)
        req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
        return try await req.rpc(
          GoogleCloudDiscoveryEngineV1.Schema.self, timeout: options.attemptTimeout
        ).get()
      }

      public func listSchemas(
        request: ListSchemasRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryEngineV1.ListSchemasResponse {
        let path = try { () throws -> Swift.String in
          guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
            throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
          }
          return "/v1/\(pathVariable0)/schemas"
        }()
        var query = [
          URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
        ]
        let encoder = GoogleCloudGax._QueryParameterEncoder()
        query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
        query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
        var req = try await self.inner.newRequest(path: path, query: query)
        req.setMethod(.GET)
        req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
        return try await req.rpc(
          GoogleCloudDiscoveryEngineV1.ListSchemasResponse.self, timeout: options.attemptTimeout
        ).get()
      }

      public func createSchema(
        request: CreateSchemaRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation {
        let path = try { () throws -> Swift.String in
          guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
            throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
          }
          return "/v1/\(pathVariable0)/schemas"
        }()
        var query = [
          URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
        ]
        let encoder = GoogleCloudGax._QueryParameterEncoder()
        query.append(contentsOf: try encoder.encode(request.schemaId, prefix: "schemaId"))
        var req = try await self.inner.newRequest(path: path, query: query)
        req.setMethod(.POST)
        req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
        if let body = request.schema {
          req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
        }
        return try await req.rpc(
          GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
        ).get()
      }

      public func updateSchema(
        request: UpdateSchemaRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation {
        let path = try { () throws -> Swift.String in
          guard let pathVariable0 = request.schema.map({ $0.name }), !pathVariable0.isEmpty else {
            throw GoogleCloudGax.RequestError.binding(
              "'request.schema.name' is not set or is empty")
          }
          return "/v1/\(pathVariable0)"
        }()
        var query = [
          URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
        ]
        let encoder = GoogleCloudGax._QueryParameterEncoder()
        query.append(contentsOf: try encoder.encode(request.allowMissing, prefix: "allowMissing"))
        var req = try await self.inner.newRequest(path: path, query: query)
        req.setMethod(.PATCH)
        req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
        if let body = request.schema {
          req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
        }
        return try await req.rpc(
          GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
        ).get()
      }

      public func deleteSchema(
        request: DeleteSchemaRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation {
        let path = try { () throws -> Swift.String in
          guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
            throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
          }
          return "/v1/\(pathVariable0)"
        }()
        let query = [
          URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
        ]
        var req = try await self.inner.newRequest(path: path, query: query)
        req.setMethod(.DELETE)
        req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
        return try await req.rpc(
          GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
        ).get()
      }

      public func listOperations(
        request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.ListOperationsResponse {
        let path = try { () throws -> Swift.String in
          guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
            throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
          }
          return "/v1/\(pathVariable0)/operations"
        }()
        var query = [
          URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
        ]
        let encoder = GoogleCloudGax._QueryParameterEncoder()
        query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
        query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
        query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
        query.append(
          contentsOf: try encoder.encode(
            request.returnPartialSuccess, prefix: "returnPartialSuccess"))
        var req = try await self.inner.newRequest(path: path, query: query)
        req.setMethod(.GET)
        req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
        return try await req.rpc(
          GoogleLongRunning.ListOperationsResponse.self, timeout: options.attemptTimeout
        ).get()
      }

      public func getOperation(
        request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation {
        let path = try { () throws -> Swift.String in
          guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
            throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
          }
          return "/v1/\(pathVariable0)"
        }()
        let query = [
          URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
        ]
        var req = try await self.inner.newRequest(path: path, query: query)
        req.setMethod(.GET)
        req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
        return try await req.rpc(
          GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
        ).get()
      }

      public func cancelOperation(
        request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws {
        let path = try { () throws -> Swift.String in
          guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
            throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
          }
          return "/v1/\(pathVariable0):cancel"
        }()
        let query = [
          URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
        ]
        var req = try await self.inner.newRequest(path: path, query: query)
        req.setMethod(.POST)
        req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
        req.setBody(data: try JSONEncoder().encode(request), ofContentType: "application/json")
        _ = try await req.rpc(
          GoogleCloudWkt.Empty.self, timeout: options.attemptTimeout
        ).get()
      }
    }
  }
#endif
