// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if ControlService || ConversationalSearchService || SearchService
  import Foundation
  import GoogleCloudWkt

  /// Promotion proto includes uri and other helping information to display the
  /// promotion.
  public struct SearchLinkPromotion: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. The title of the promotion.
    /// Maximum length: 160 characters.
    public var title: Swift.String = Swift.String()

    /// Optional. The URL for the page the user wants to promote. Must be set for
    /// site search. For other verticals, this is optional.
    public var uri: Swift.String = Swift.String()

    /// Optional. The [Document][google.cloud.discoveryengine.v1.Document] the user
    /// wants to promote. For site search, leave unset and only populate uri. Can
    /// be set along with uri.
    ///
    /// [google.cloud.discoveryengine.v1.Document]: <doc:Document>
    public var document: Swift.String = Swift.String()

    /// Optional. The promotion thumbnail image url.
    public var imageUri: Swift.String = Swift.String()

    /// Optional. The Promotion description.
    /// Maximum length: 200 characters.
    public var description: Swift.String = Swift.String()

    /// Optional. The enabled promotion will be returned for any serving configs
    /// associated with the parent of the control this promotion is attached to.
    ///
    /// This flag is used for basic site search only.
    public var enabled: Swift.Bool = Swift.Bool()

    /// Initialize a new instance of `SearchLinkPromotion`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SearchLinkPromotion().with { $0.title = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.discoveryengine.v1.SearchLinkPromotion"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
