// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if ServingConfigService
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  @_spi(GoogleCloudInternal) public import GoogleLongRunning
  @_spi(GoogleCloudInternal) public import GoogleWKT
  @_spi(GoogleCloudInternal) public import GoogleGax

  /// Service for operations related to
  /// [ServingConfig][google.cloud.discoveryengine.v1.ServingConfig].
  ///
  /// [google.cloud.discoveryengine.v1.ServingConfig]: <doc:ServingConfig>
  ///
  /// @Snippet(path: "ServingConfigServiceQuickstart")
  public final class ServingConfigServiceClient: Clients.ServingConfigServiceProtocol, Sendable {
    let inner: any Clients.ServingConfigServiceStub

    /// Creates a new `ServingConfigServiceClient` instance.
    public init(_ options: GoogleGax.ClientOptions = .init()) throws {
      var inner: any Clients.ServingConfigServiceStub = try Clients.ServingConfigServiceTransport(
        options)
      inner = Clients.ServingConfigServiceRetry(inner, options: options)
      if let logger = options.logger {
        inner = Clients.ServingConfigServiceLogging(inner, logger: logger)
      }
      self.inner = inner
    }

    /// Updates a ServingConfig.
    ///
    /// Returns a NOT_FOUND error if the ServingConfig does not exist.
    ///
    /// @Snippet(path: "ServingConfigService_UpdateServingConfig")
    public func updateServingConfig(
      request: UpdateServingConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDiscoveryEngineV1.ServingConfig {
      try await self.inner.updateServingConfig(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "ServingConfigService_ListOperations")
    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self.inner.listOperations(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "ServingConfigService_GetOperation")
    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self.inner.getOperation(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "ServingConfigService_CancelOperation")
    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self.inner.cancelOperation(request: request, options: options)
    }
  }

  extension Clients {
    /// A Swift protocol to mock `ServingConfigServiceClient`.
    ///
    /// To mock `ServingConfigServiceClient` change your functions to receive
    /// `some ServingConfigServiceProtocol` or `any ServingConfigServiceProtocol`
    /// and pass a mock implementation in your tests.
    public protocol ServingConfigServiceProtocol: Sendable {
      /// See `ServingConfigServiceClient.updateServingConfig`.
      func updateServingConfig(
        request: UpdateServingConfigRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryEngineV1.ServingConfig

      /// See `ServingConfigServiceClient.listOperations`.
      func listOperations(
        request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.ListOperationsResponse

      /// See `ServingConfigServiceClient.cancelOperation`.
      func cancelOperation(
        request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
      ) async throws
    }
  }

  // Default implementations
  extension Clients.ServingConfigServiceProtocol {
    public func updateServingConfig(request: UpdateServingConfigRequest) async throws
      -> GoogleCloudDiscoveryEngineV1.ServingConfig
    {
      try await self.updateServingConfig(request: request, options: .init())
    }

    public func updateServingConfig(
      request: UpdateServingConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDiscoveryEngineV1.ServingConfig {
      throw GoogleGax.RequestError.unimplemented
    }

    public func updateServingConfig(
      servingConfig: ServingConfig?,
      updateMask: GoogleWKT.WKTFieldMask?,
    ) async throws -> GoogleCloudDiscoveryEngineV1.ServingConfig {
      let request = UpdateServingConfigRequest().with {
        $0.servingConfig = servingConfig
        $0.updateMask = updateMask
      }
      return try await self.updateServingConfig(request: request)
    }

    public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse
    {
      try await self.listOperations(request: request, options: .init())
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func listOperationsByItems(
      request: GoogleLongRunning.ListOperationsRequest
    ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
      self.listOperationsByItems(request: request, options: .init())
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "ServingConfigService_ListOperations")
    public func listOperationsByItems(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
      let listRpc = {
        @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
        var request = request
        request.pageToken = token
        return try await self.listOperations(request: request, options: options)
      }
      return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func listOperationsByItems(
      name: Swift.String,
      filter: Swift.String,
    ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
      let request = GoogleLongRunning.ListOperationsRequest().with {
        $0.name = name
        $0.filter = filter
      }
      return self.listOperationsByItems(request: request)
    }

    public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
      -> GoogleLongRunning.Operation
    {
      try await self.getOperation(request: request, options: .init())
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func getOperation(
      name: Swift.String,
    ) async throws -> GoogleLongRunning.Operation {
      let request = GoogleLongRunning.GetOperationRequest().with {
        $0.name = name
      }
      return try await self.getOperation(request: request)
    }

    public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
      try await self.cancelOperation(request: request, options: .init())
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      throw GoogleGax.RequestError.unimplemented
    }

    public func cancelOperation(
      name: Swift.String,
    ) async throws {
      let request = GoogleLongRunning.CancelOperationRequest().with {
        $0.name = name
      }
      try await self.cancelOperation(request: request)
    }
  }
#else
  @_spi(GoogleCloudInternal) public import GoogleGax

  @available(
    *, unavailable,
    message: "Enable the 'ServingConfigService' trait in Package.swift to use this client."
  )
  public final class ServingConfigServiceClient: Sendable {
    @available(
      *, unavailable,
      message: "Enable the 'ServingConfigService' trait in Package.swift to use this client."
    )
    public init(_ options: GoogleGax.ClientOptions = .init()) throws {}
  }
#endif
