// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if ConversationalSearchService || SessionService
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWkt

  /// External session proto definition.
  public struct Session: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Immutable. Fully qualified name
    /// `projects/{project}/locations/global/collections/{collection}/engines/{engine}/sessions/*`
    public var name: Swift.String = Swift.String()

    /// Optional. The display name of the session.
    ///
    /// This field is used to identify the session in the UI.
    /// By default, the display name is the first turn query text in the session.
    public var displayName: Swift.String = Swift.String()

    /// The state of the session.
    public var state: Session.State = Session.State()

    /// A unique identifier for tracking users.
    public var userPseudoId: Swift.String = Swift.String()

    /// Turns.
    public var turns: [Session.Turn] = []

    /// Optional. The labels for the session.
    /// Can be set as filter in ListSessionsRequest.
    public var labels: [Swift.String] = []

    /// Output only. The time the session started.
    public var startTime: GoogleCloudWkt.Timestamp? = nil

    /// Output only. The time the session finished.
    public var endTime: GoogleCloudWkt.Timestamp? = nil

    /// Optional. Whether the session is pinned, pinned session will be displayed
    /// on the top of the session list.
    public var isPinned: Swift.Bool = Swift.Bool()

    /// Initialize a new instance of `Session`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Session().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Represents a turn, including a query from the user and a
    /// answer from service.
    public struct Turn: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Optional. The user query. May not be set if this turn is merely
      /// regenerating an answer to a different turn
      public var query: Query? = nil

      /// Optional. The resource name of the answer to the user query.
      ///
      /// Only set if the answer generation (/answer API call) happened in this
      /// turn.
      public var answer: Swift.String = Swift.String()

      /// Output only. In
      /// [ConversationalSearchService.GetSession][google.cloud.discoveryengine.v1.ConversationalSearchService.GetSession]
      /// API, if
      /// [GetSessionRequest.include_answer_details][google.cloud.discoveryengine.v1.GetSessionRequest.include_answer_details]
      /// is set to true, this field will be populated when getting answer query
      /// session.
      ///
      /// [google.cloud.discoveryengine.v1.ConversationalSearchService.GetSession]: <doc:ConversationalSearchServiceClient/getSession(request:options:)>
      /// [google.cloud.discoveryengine.v1.GetSessionRequest.include_answer_details]: <doc:GetSessionRequest/includeAnswerDetails>
      public var detailedAnswer: Answer? = nil

      /// Output only. In
      /// [ConversationalSearchService.GetSession][google.cloud.discoveryengine.v1.ConversationalSearchService.GetSession]
      /// API, if
      /// [GetSessionRequest.include_answer_details][google.cloud.discoveryengine.v1.GetSessionRequest.include_answer_details]
      /// is set to true, this field will be populated when getting assistant
      /// session.
      ///
      /// [google.cloud.discoveryengine.v1.ConversationalSearchService.GetSession]: <doc:ConversationalSearchServiceClient/getSession(request:options:)>
      /// [google.cloud.discoveryengine.v1.GetSessionRequest.include_answer_details]: <doc:GetSessionRequest/includeAnswerDetails>
      public var detailedAssistAnswer: AssistAnswer? = nil

      /// Optional. Represents metadata related to the query config, for example
      /// LLM model and version used, model parameters (temperature, grounding
      /// parameters, etc.). The prefix "google." is reserved for Google-developed
      /// functionality.
      public var queryConfig: [Swift.String: Swift.String] = [:]

      /// Initialize a new instance of `Turn`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Turn().with { $0.query = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.discoveryengine.v1.Session.Turn"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Enumeration of the state of the session.
    public enum State: Codable, Equatable, Sendable {
      /// State is unspecified.
      case unspecified
      /// The session is currently open.
      case inProgress
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .inProgress: return 1
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "STATE_UNSPECIFIED"
        case .inProgress: return "IN_PROGRESS"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "STATE_UNSPECIFIED": self = .unspecified
        case "IN_PROGRESS": self = .inProgress
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .inProgress
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .inProgress: return try container.encode(1)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.discoveryengine.v1.Session"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
