// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SiteSearchEngineService
  import Foundation
  import GoogleCloudWKT
  import GoogleLongRunning
  import GoogleRpc
  import GoogleCloudGax

  extension Clients {
    protocol SiteSearchEngineServiceStub: Sendable {
      func getSiteSearchEngine(
        request: GetSiteSearchEngineRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryEngineV1.SiteSearchEngine

      func createTargetSite(
        request: CreateTargetSiteRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      func batchCreateTargetSites(
        request: BatchCreateTargetSitesRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      func getTargetSite(
        request: GetTargetSiteRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryEngineV1.TargetSite

      func updateTargetSite(
        request: UpdateTargetSiteRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      func deleteTargetSite(
        request: DeleteTargetSiteRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      func listTargetSites(
        request: ListTargetSitesRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryEngineV1.ListTargetSitesResponse

      func createSitemap(
        request: CreateSitemapRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      func deleteSitemap(
        request: DeleteSitemapRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      func fetchSitemaps(
        request: FetchSitemapsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryEngineV1.FetchSitemapsResponse

      func enableAdvancedSiteSearch(
        request: EnableAdvancedSiteSearchRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      func disableAdvancedSiteSearch(
        request: DisableAdvancedSiteSearchRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      func recrawlUris(
        request: RecrawlUrisRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      func batchVerifyTargetSites(
        request: BatchVerifyTargetSitesRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      func fetchDomainVerificationStatus(
        request: FetchDomainVerificationStatusRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryEngineV1.FetchDomainVerificationStatusResponse

      func listOperations(
        request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.ListOperationsResponse

      func getOperation(
        request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      func cancelOperation(
        request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws
    }
  }
#endif
