// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SiteSearchEngineService
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  import GoogleCloudWkt
  import GoogleLongrunning
  import GoogleRpc
  import GoogleCloudGax

  extension Clients {
    final class SiteSearchEngineServiceRetry: SiteSearchEngineServiceStub {
      let inner: any SiteSearchEngineServiceStub
      let options: GoogleCloudGax.ClientOptions

      public init(_ inner: any SiteSearchEngineServiceStub, options: GoogleCloudGax.ClientOptions) {
        self.inner = inner
        self.options = options
      }

      func _intercept<Input, Output>(
        request: Input,
        options: GoogleCloudGax.RequestOptions,
        idempotent: Swift.Bool,
        action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
      ) async throws -> Output {
        let loop = GoogleCloudGax._RetryLoop(
          options: options, withDefault: self.options, idempotent: idempotent,
        )
        let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
          var attemptOptions = options
          attemptOptions.attemptTimeout = attemptTimeout
          return try await action(request, attemptOptions)
        }
        return try await loop.run(attempt: attempt)
      }

      public func getSiteSearchEngine(
        request: GetSiteSearchEngineRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.SiteSearchEngine {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: GetSiteSearchEngineRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudDiscoveryengineV1.SiteSearchEngine
            in
            return try await self.inner.getSiteSearchEngine(request: r, options: o)
          })
      }

      public func createTargetSite(
        request: CreateTargetSiteRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongrunning.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: CreateTargetSiteRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleLongrunning.Operation
            in
            return try await self.inner.createTargetSite(request: r, options: o)
          })
      }

      public func batchCreateTargetSites(
        request: BatchCreateTargetSitesRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongrunning.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: BatchCreateTargetSitesRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleLongrunning.Operation
            in
            return try await self.inner.batchCreateTargetSites(request: r, options: o)
          })
      }

      public func getTargetSite(
        request: GetTargetSiteRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.TargetSite {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: GetTargetSiteRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudDiscoveryengineV1.TargetSite
            in
            return try await self.inner.getTargetSite(request: r, options: o)
          })
      }

      public func updateTargetSite(
        request: UpdateTargetSiteRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongrunning.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: UpdateTargetSiteRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleLongrunning.Operation
            in
            return try await self.inner.updateTargetSite(request: r, options: o)
          })
      }

      public func deleteTargetSite(
        request: DeleteTargetSiteRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongrunning.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: DeleteTargetSiteRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleLongrunning.Operation
            in
            return try await self.inner.deleteTargetSite(request: r, options: o)
          })
      }

      public func listTargetSites(
        request: ListTargetSitesRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.ListTargetSitesResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: ListTargetSitesRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudDiscoveryengineV1.ListTargetSitesResponse
            in
            return try await self.inner.listTargetSites(request: r, options: o)
          })
      }

      public func createSitemap(
        request: CreateSitemapRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongrunning.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: CreateSitemapRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleLongrunning.Operation
            in
            return try await self.inner.createSitemap(request: r, options: o)
          })
      }

      public func deleteSitemap(
        request: DeleteSitemapRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongrunning.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: DeleteSitemapRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleLongrunning.Operation
            in
            return try await self.inner.deleteSitemap(request: r, options: o)
          })
      }

      public func fetchSitemaps(
        request: FetchSitemapsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.FetchSitemapsResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: FetchSitemapsRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudDiscoveryengineV1.FetchSitemapsResponse
            in
            return try await self.inner.fetchSitemaps(request: r, options: o)
          })
      }

      public func enableAdvancedSiteSearch(
        request: EnableAdvancedSiteSearchRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongrunning.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: EnableAdvancedSiteSearchRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleLongrunning.Operation
            in
            return try await self.inner.enableAdvancedSiteSearch(request: r, options: o)
          })
      }

      public func disableAdvancedSiteSearch(
        request: DisableAdvancedSiteSearchRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongrunning.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: DisableAdvancedSiteSearchRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleLongrunning.Operation
            in
            return try await self.inner.disableAdvancedSiteSearch(request: r, options: o)
          })
      }

      public func recrawlUris(
        request: RecrawlUrisRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongrunning.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: RecrawlUrisRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleLongrunning.Operation
            in
            return try await self.inner.recrawlUris(request: r, options: o)
          })
      }

      public func batchVerifyTargetSites(
        request: BatchVerifyTargetSitesRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongrunning.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: BatchVerifyTargetSitesRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleLongrunning.Operation
            in
            return try await self.inner.batchVerifyTargetSites(request: r, options: o)
          })
      }

      public func fetchDomainVerificationStatus(
        request: FetchDomainVerificationStatusRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDiscoveryengineV1.FetchDomainVerificationStatusResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: FetchDomainVerificationStatusRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudDiscoveryengineV1.FetchDomainVerificationStatusResponse
            in
            return try await self.inner.fetchDomainVerificationStatus(request: r, options: o)
          })
      }

      public func listOperations(
        request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongrunning.ListOperationsResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: GoogleLongrunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleLongrunning.ListOperationsResponse
            in
            return try await self.inner.listOperations(request: r, options: o)
          })
      }

      public func getOperation(
        request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongrunning.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: GoogleLongrunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleLongrunning.Operation
            in
            return try await self.inner.getOperation(request: r, options: o)
          })
      }

      public func cancelOperation(
        request: GoogleLongrunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: GoogleLongrunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> Void in
            return try await self.inner.cancelOperation(request: r, options: o)
          })
      }
    }
  }
#endif
